#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("C1Gauge101.Resource", IsApplication=true)]

namespace C1Gauge101
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::C1.Android.Core.Resource.Attribute.c1_backgroundColor = global::C1Gauge101.Resource.Attribute.c1_backgroundColor;
			global::C1.Android.Core.Resource.Attribute.c1_borderColor = global::C1Gauge101.Resource.Attribute.c1_borderColor;
			global::C1.Android.Core.Resource.Attribute.c1_fontFamily = global::C1Gauge101.Resource.Attribute.c1_fontFamily;
			global::C1.Android.Core.Resource.Attribute.c1_selectedIndex = global::C1Gauge101.Resource.Attribute.c1_selectedIndex;
			global::C1.Android.Core.Resource.Attribute.c1_selectionBackgroundColor = global::C1Gauge101.Resource.Attribute.c1_selectionBackgroundColor;
			global::C1.Android.Core.Resource.Attribute.c1_selectionTextColor = global::C1Gauge101.Resource.Attribute.c1_selectionTextColor;
			global::C1.Android.Core.Resource.Attribute.c1_textColor = global::C1Gauge101.Resource.Attribute.c1_textColor;
			global::C1.Android.Core.Resource.Attribute.c1_textSize = global::C1Gauge101.Resource.Attribute.c1_textSize;
			global::C1.Android.Core.Resource.Attribute.c1_textStyle = global::C1Gauge101.Resource.Attribute.c1_textStyle;
			global::C1.Android.Core.Resource.Attribute.c1_typeface = global::C1Gauge101.Resource.Attribute.c1_typeface;
			global::C1.Android.Core.Resource.Id.bold = global::C1Gauge101.Resource.Id.bold;
			global::C1.Android.Core.Resource.Id.italic = global::C1Gauge101.Resource.Id.italic;
			global::C1.Android.Core.Resource.Id.monospace = global::C1Gauge101.Resource.Id.monospace;
			global::C1.Android.Core.Resource.Id.normal = global::C1Gauge101.Resource.Id.normal;
			global::C1.Android.Core.Resource.Id.sans = global::C1Gauge101.Resource.Id.sans;
			global::C1.Android.Core.Resource.Id.serif = global::C1Gauge101.Resource.Id.serif;
			global::C1.Android.Gauge.Resource.Attribute.c1_backgroundColor = global::C1Gauge101.Resource.Attribute.c1_backgroundColor;
			global::C1.Android.Gauge.Resource.Attribute.c1_borderColor = global::C1Gauge101.Resource.Attribute.c1_borderColor;
			global::C1.Android.Gauge.Resource.Attribute.c1_fontFamily = global::C1Gauge101.Resource.Attribute.c1_fontFamily;
			global::C1.Android.Gauge.Resource.Attribute.c1_selectedIndex = global::C1Gauge101.Resource.Attribute.c1_selectedIndex;
			global::C1.Android.Gauge.Resource.Attribute.c1_selectionBackgroundColor = global::C1Gauge101.Resource.Attribute.c1_selectionBackgroundColor;
			global::C1.Android.Gauge.Resource.Attribute.c1_selectionTextColor = global::C1Gauge101.Resource.Attribute.c1_selectionTextColor;
			global::C1.Android.Gauge.Resource.Attribute.c1_textColor = global::C1Gauge101.Resource.Attribute.c1_textColor;
			global::C1.Android.Gauge.Resource.Attribute.c1_textSize = global::C1Gauge101.Resource.Attribute.c1_textSize;
			global::C1.Android.Gauge.Resource.Attribute.c1_textStyle = global::C1Gauge101.Resource.Attribute.c1_textStyle;
			global::C1.Android.Gauge.Resource.Attribute.c1_typeface = global::C1Gauge101.Resource.Attribute.c1_typeface;
			global::C1.Android.Gauge.Resource.Id.bold = global::C1Gauge101.Resource.Id.bold;
			global::C1.Android.Gauge.Resource.Id.italic = global::C1Gauge101.Resource.Id.italic;
			global::C1.Android.Gauge.Resource.Id.monospace = global::C1Gauge101.Resource.Id.monospace;
			global::C1.Android.Gauge.Resource.Id.normal = global::C1Gauge101.Resource.Id.normal;
			global::C1.Android.Gauge.Resource.Id.sans = global::C1Gauge101.Resource.Id.sans;
			global::C1.Android.Gauge.Resource.Id.serif = global::C1Gauge101.Resource.Id.serif;
			global::C1.Android.Gauge.Resource.Styleable.C1Gauge = global::C1Gauge101.Resource.Styleable.C1Gauge;
			global::C1.Android.Gauge.Resource.Styleable.C1Gauge_c1_backgroundColor = global::C1Gauge101.Resource.Styleable.C1Gauge_c1_backgroundColor;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int directionSpinnerValues = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int showTextSpinnerValues = 2131034113;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int c1_backgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010006
			public const int c1_borderColor = 2130771974;
			
			// aapt resource value: 0x7f010004
			public const int c1_fontFamily = 2130771972;
			
			// aapt resource value: 0x7f010009
			public const int c1_selectedIndex = 2130771977;
			
			// aapt resource value: 0x7f010007
			public const int c1_selectionBackgroundColor = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int c1_selectionTextColor = 2130771976;
			
			// aapt resource value: 0x7f010001
			public const int c1_textColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int c1_textSize = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int c1_textStyle = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int c1_typeface = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int gauge_basic = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int gauge_bullet = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int gauge_linear = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int gauge_radial = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int gauge_ranges = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int gauge_scaling = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_launcher = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000d
			public const int badText = 2131099661;
			
			// aapt resource value: 0x7f060000
			public const int bold = 2131099648;
			
			// aapt resource value: 0x7f060016
			public const int bulletGraph1 = 2131099670;
			
			// aapt resource value: 0x7f060027
			public const int bulletgraph = 2131099687;
			
			// aapt resource value: 0x7f06000e
			public const int buttonBadMinus = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int buttonBadPlus = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int buttonGoodMinus = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int buttonGoodPlus = 2131099666;
			
			// aapt resource value: 0x7f060020
			public const int buttonMinus = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int buttonPlus = 2131099681;
			
			// aapt resource value: 0x7f060007
			public const int buttonStartMinus = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int buttonStartPlus = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int buttonSweepMinus = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int buttonSweepPlus = 2131099659;
			
			// aapt resource value: 0x7f060014
			public const int buttonTargetMinus = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int buttonTargetPlus = 2131099669;
			
			// aapt resource value: 0x7f060022
			public const int buttonValueMinus = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int buttonValuePlus = 2131099683;
			
			// aapt resource value: 0x7f06001c
			public const int directionSpinner = 2131099676;
			
			// aapt resource value: 0x7f060010
			public const int goodText = 2131099664;
			
			// aapt resource value: 0x7f060001
			public const int italic = 2131099649;
			
			// aapt resource value: 0x7f06001d
			public const int layout1 = 2131099677;
			
			// aapt resource value: 0x7f060017
			public const int linearGauge1 = 2131099671;
			
			// aapt resource value: 0x7f060026
			public const int lineargauge = 2131099686;
			
			// aapt resource value: 0x7f060024
			public const int listView1 = 2131099684;
			
			// aapt resource value: 0x7f060003
			public const int monospace = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int normal = 2131099650;
			
			// aapt resource value: 0x7f06000c
			public const int radialGauge1 = 2131099660;
			
			// aapt resource value: 0x7f060028
			public const int radialgauge = 2131099688;
			
			// aapt resource value: 0x7f06001b
			public const int sampleDesc = 2131099675;
			
			// aapt resource value: 0x7f060019
			public const int sampleImage = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int sampleName = 2131099674;
			
			// aapt resource value: 0x7f060018
			public const int sample_list = 2131099672;
			
			// aapt resource value: 0x7f060004
			public const int sans = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int serif = 2131099653;
			
			// aapt resource value: 0x7f06001e
			public const int showTextSpinner = 2131099678;
			
			// aapt resource value: 0x7f060006
			public const int startAngleText = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int sweepAngleText = 2131099657;
			
			// aapt resource value: 0x7f060025
			public const int switchRange = 2131099685;
			
			// aapt resource value: 0x7f060013
			public const int targetText = 2131099667;
			
			// aapt resource value: 0x7f06001f
			public const int valueText = 2131099679;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_automatic_scaling = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_bullet_graph = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_custom_animation = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_custom_list = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int activity_direction = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int activity_displaying_values = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int activity_getting_started = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int activity_main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int activity_using_ranges = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Main = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int automatic_scaling = 2130968577;
			
			// aapt resource value: 0x7f040018
			public const int automatic_scaling_desc = 2130968600;
			
			// aapt resource value: 0x7f04000c
			public const int bad = 2130968588;
			
			// aapt resource value: 0x7f040002
			public const int bullet_graph = 2130968578;
			
			// aapt resource value: 0x7f040011
			public const int bulletgraph = 2130968593;
			
			// aapt resource value: 0x7f04001a
			public const int bulletgraph_desc = 2130968602;
			
			// aapt resource value: 0x7f040003
			public const int custom_animation = 2130968579;
			
			// aapt resource value: 0x7f04001b
			public const int custom_animation_desc = 2130968603;
			
			// aapt resource value: 0x7f040004
			public const int direction = 2130968580;
			
			// aapt resource value: 0x7f040019
			public const int direction_desc = 2130968601;
			
			// aapt resource value: 0x7f040005
			public const int displaying_values = 2130968581;
			
			// aapt resource value: 0x7f040016
			public const int displaying_values_desc = 2130968598;
			
			// aapt resource value: 0x7f040006
			public const int getting_started = 2130968582;
			
			// aapt resource value: 0x7f040015
			public const int getting_started_desc = 2130968597;
			
			// aapt resource value: 0x7f04000d
			public const int good = 2130968589;
			
			// aapt resource value: 0x7f040013
			public const int lineargauge = 2130968595;
			
			// aapt resource value: 0x7f04000b
			public const int minus = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int plus = 2130968586;
			
			// aapt resource value: 0x7f040012
			public const int radialgauge = 2130968594;
			
			// aapt resource value: 0x7f040014
			public const int show_ranges = 2130968596;
			
			// aapt resource value: 0x7f04000f
			public const int show_text = 2130968591;
			
			// aapt resource value: 0x7f040008
			public const int start_angle = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int sweep_angle = 2130968585;
			
			// aapt resource value: 0x7f04000e
			public const int target = 2130968590;
			
			// aapt resource value: 0x7f040007
			public const int using_ranges = 2130968583;
			
			// aapt resource value: 0x7f040017
			public const int using_ranges_desc = 2130968599;
			
			// aapt resource value: 0x7f040010
			public const int value = 2130968592;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] C1Gauge = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int C1Gauge_c1_backgroundColor = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
