#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FlexGrid101.Android.Resource", IsApplication=true)]

namespace FlexGrid101.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::C1.Android.Core.Resource.Attribute.c1_backgroundColor = global::FlexGrid101.Android.Resource.Attribute.c1_backgroundColor;
			global::C1.Android.Core.Resource.Attribute.c1_borderColor = global::FlexGrid101.Android.Resource.Attribute.c1_borderColor;
			global::C1.Android.Core.Resource.Attribute.c1_fontFamily = global::FlexGrid101.Android.Resource.Attribute.c1_fontFamily;
			global::C1.Android.Core.Resource.Attribute.c1_selectedIndex = global::FlexGrid101.Android.Resource.Attribute.c1_selectedIndex;
			global::C1.Android.Core.Resource.Attribute.c1_selectionBackgroundColor = global::FlexGrid101.Android.Resource.Attribute.c1_selectionBackgroundColor;
			global::C1.Android.Core.Resource.Attribute.c1_selectionTextColor = global::FlexGrid101.Android.Resource.Attribute.c1_selectionTextColor;
			global::C1.Android.Core.Resource.Attribute.c1_textColor = global::FlexGrid101.Android.Resource.Attribute.c1_textColor;
			global::C1.Android.Core.Resource.Attribute.c1_textSize = global::FlexGrid101.Android.Resource.Attribute.c1_textSize;
			global::C1.Android.Core.Resource.Attribute.c1_textStyle = global::FlexGrid101.Android.Resource.Attribute.c1_textStyle;
			global::C1.Android.Core.Resource.Attribute.c1_typeface = global::FlexGrid101.Android.Resource.Attribute.c1_typeface;
			global::C1.Android.Core.Resource.Id.bold = global::FlexGrid101.Android.Resource.Id.bold;
			global::C1.Android.Core.Resource.Id.italic = global::FlexGrid101.Android.Resource.Id.italic;
			global::C1.Android.Core.Resource.Id.monospace = global::FlexGrid101.Android.Resource.Id.monospace;
			global::C1.Android.Core.Resource.Id.normal = global::FlexGrid101.Android.Resource.Id.normal;
			global::C1.Android.Core.Resource.Id.sans = global::FlexGrid101.Android.Resource.Id.sans;
			global::C1.Android.Core.Resource.Id.serif = global::FlexGrid101.Android.Resource.Id.serif;
			global::C1.Android.Gauge.Resource.Attribute.c1_backgroundColor = global::FlexGrid101.Android.Resource.Attribute.c1_backgroundColor;
			global::C1.Android.Gauge.Resource.Attribute.c1_borderColor = global::FlexGrid101.Android.Resource.Attribute.c1_borderColor;
			global::C1.Android.Gauge.Resource.Attribute.c1_fontFamily = global::FlexGrid101.Android.Resource.Attribute.c1_fontFamily;
			global::C1.Android.Gauge.Resource.Attribute.c1_selectedIndex = global::FlexGrid101.Android.Resource.Attribute.c1_selectedIndex;
			global::C1.Android.Gauge.Resource.Attribute.c1_selectionBackgroundColor = global::FlexGrid101.Android.Resource.Attribute.c1_selectionBackgroundColor;
			global::C1.Android.Gauge.Resource.Attribute.c1_selectionTextColor = global::FlexGrid101.Android.Resource.Attribute.c1_selectionTextColor;
			global::C1.Android.Gauge.Resource.Attribute.c1_textColor = global::FlexGrid101.Android.Resource.Attribute.c1_textColor;
			global::C1.Android.Gauge.Resource.Attribute.c1_textSize = global::FlexGrid101.Android.Resource.Attribute.c1_textSize;
			global::C1.Android.Gauge.Resource.Attribute.c1_textStyle = global::FlexGrid101.Android.Resource.Attribute.c1_textStyle;
			global::C1.Android.Gauge.Resource.Attribute.c1_typeface = global::FlexGrid101.Android.Resource.Attribute.c1_typeface;
			global::C1.Android.Gauge.Resource.Id.bold = global::FlexGrid101.Android.Resource.Id.bold;
			global::C1.Android.Gauge.Resource.Id.italic = global::FlexGrid101.Android.Resource.Id.italic;
			global::C1.Android.Gauge.Resource.Id.monospace = global::FlexGrid101.Android.Resource.Id.monospace;
			global::C1.Android.Gauge.Resource.Id.normal = global::FlexGrid101.Android.Resource.Id.normal;
			global::C1.Android.Gauge.Resource.Id.sans = global::FlexGrid101.Android.Resource.Id.sans;
			global::C1.Android.Gauge.Resource.Id.serif = global::FlexGrid101.Android.Resource.Id.serif;
			global::C1.Android.Gauge.Resource.Styleable.C1Gauge = global::FlexGrid101.Android.Resource.Styleable.C1Gauge;
			global::C1.Android.Gauge.Resource.Styleable.C1Gauge_c1_backgroundColor = global::FlexGrid101.Android.Resource.Styleable.C1Gauge_c1_backgroundColor;
			global::C1.Android.Grid.Resource.Attribute.c1_allowMerging = global::FlexGrid101.Android.Resource.Attribute.c1_allowMerging;
			global::C1.Android.Grid.Resource.Attribute.c1_alternatingRowBackgroundColor = global::FlexGrid101.Android.Resource.Attribute.c1_alternatingRowBackgroundColor;
			global::C1.Android.Grid.Resource.Attribute.c1_autoGenerateColumns = global::FlexGrid101.Android.Resource.Attribute.c1_autoGenerateColumns;
			global::C1.Android.Grid.Resource.Attribute.c1_autoSizeMode = global::FlexGrid101.Android.Resource.Attribute.c1_autoSizeMode;
			global::C1.Android.Grid.Resource.Attribute.c1_backgroundColor = global::FlexGrid101.Android.Resource.Attribute.c1_backgroundColor;
			global::C1.Android.Grid.Resource.Attribute.c1_borderColor = global::FlexGrid101.Android.Resource.Attribute.c1_borderColor;
			global::C1.Android.Grid.Resource.Attribute.c1_columnHeaderBackgroundColor = global::FlexGrid101.Android.Resource.Attribute.c1_columnHeaderBackgroundColor;
			global::C1.Android.Grid.Resource.Attribute.c1_columnHeaderSelectedBackgroundColor = global::FlexGrid101.Android.Resource.Attribute.c1_columnHeaderSelectedBackgroundColor;
			global::C1.Android.Grid.Resource.Attribute.c1_columnHeaderTextColor = global::FlexGrid101.Android.Resource.Attribute.c1_columnHeaderTextColor;
			global::C1.Android.Grid.Resource.Attribute.c1_cursorBackgroundColor = global::FlexGrid101.Android.Resource.Attribute.c1_cursorBackgroundColor;
			global::C1.Android.Grid.Resource.Attribute.c1_cursorTextColor = global::FlexGrid101.Android.Resource.Attribute.c1_cursorTextColor;
			global::C1.Android.Grid.Resource.Attribute.c1_defaultRowHeight = global::FlexGrid101.Android.Resource.Attribute.c1_defaultRowHeight;
			global::C1.Android.Grid.Resource.Attribute.c1_editorBackgroundColor = global::FlexGrid101.Android.Resource.Attribute.c1_editorBackgroundColor;
			global::C1.Android.Grid.Resource.Attribute.c1_editorTextColor = global::FlexGrid101.Android.Resource.Attribute.c1_editorTextColor;
			global::C1.Android.Grid.Resource.Attribute.c1_fontFamily = global::FlexGrid101.Android.Resource.Attribute.c1_fontFamily;
			global::C1.Android.Grid.Resource.Attribute.c1_frozenColumns = global::FlexGrid101.Android.Resource.Attribute.c1_frozenColumns;
			global::C1.Android.Grid.Resource.Attribute.c1_frozenRows = global::FlexGrid101.Android.Resource.Attribute.c1_frozenRows;
			global::C1.Android.Grid.Resource.Attribute.c1_gridLinesColor = global::FlexGrid101.Android.Resource.Attribute.c1_gridLinesColor;
			global::C1.Android.Grid.Resource.Attribute.c1_gridLinesVisibility = global::FlexGrid101.Android.Resource.Attribute.c1_gridLinesVisibility;
			global::C1.Android.Grid.Resource.Attribute.c1_gridSelectionMode = global::FlexGrid101.Android.Resource.Attribute.c1_gridSelectionMode;
			global::C1.Android.Grid.Resource.Attribute.c1_headerGridLinesColor = global::FlexGrid101.Android.Resource.Attribute.c1_headerGridLinesColor;
			global::C1.Android.Grid.Resource.Attribute.c1_headersGridLinesVisibility = global::FlexGrid101.Android.Resource.Attribute.c1_headersGridLinesVisibility;
			global::C1.Android.Grid.Resource.Attribute.c1_headersVisibility = global::FlexGrid101.Android.Resource.Attribute.c1_headersVisibility;
			global::C1.Android.Grid.Resource.Attribute.c1_isReadOnly = global::FlexGrid101.Android.Resource.Attribute.c1_isReadOnly;
			global::C1.Android.Grid.Resource.Attribute.c1_rowBackgroundColor = global::FlexGrid101.Android.Resource.Attribute.c1_rowBackgroundColor;
			global::C1.Android.Grid.Resource.Attribute.c1_rowHeaderBackgroundColor = global::FlexGrid101.Android.Resource.Attribute.c1_rowHeaderBackgroundColor;
			global::C1.Android.Grid.Resource.Attribute.c1_rowHeaderSelectedBackgroundColor = global::FlexGrid101.Android.Resource.Attribute.c1_rowHeaderSelectedBackgroundColor;
			global::C1.Android.Grid.Resource.Attribute.c1_rowHeaderTextColor = global::FlexGrid101.Android.Resource.Attribute.c1_rowHeaderTextColor;
			global::C1.Android.Grid.Resource.Attribute.c1_selectedIndex = global::FlexGrid101.Android.Resource.Attribute.c1_selectedIndex;
			global::C1.Android.Grid.Resource.Attribute.c1_selectionAdornerBorderColor = global::FlexGrid101.Android.Resource.Attribute.c1_selectionAdornerBorderColor;
			global::C1.Android.Grid.Resource.Attribute.c1_selectionAdornerColor = global::FlexGrid101.Android.Resource.Attribute.c1_selectionAdornerColor;
			global::C1.Android.Grid.Resource.Attribute.c1_selectionBackgroundColor = global::FlexGrid101.Android.Resource.Attribute.c1_selectionBackgroundColor;
			global::C1.Android.Grid.Resource.Attribute.c1_selectionTextColor = global::FlexGrid101.Android.Resource.Attribute.c1_selectionTextColor;
			global::C1.Android.Grid.Resource.Attribute.c1_showMarquee = global::FlexGrid101.Android.Resource.Attribute.c1_showMarquee;
			global::C1.Android.Grid.Resource.Attribute.c1_showOutlineBar = global::FlexGrid101.Android.Resource.Attribute.c1_showOutlineBar;
			global::C1.Android.Grid.Resource.Attribute.c1_textColor = global::FlexGrid101.Android.Resource.Attribute.c1_textColor;
			global::C1.Android.Grid.Resource.Attribute.c1_textSize = global::FlexGrid101.Android.Resource.Attribute.c1_textSize;
			global::C1.Android.Grid.Resource.Attribute.c1_textStyle = global::FlexGrid101.Android.Resource.Attribute.c1_textStyle;
			global::C1.Android.Grid.Resource.Attribute.c1_topLeftCellBackgroundColor = global::FlexGrid101.Android.Resource.Attribute.c1_topLeftCellBackgroundColor;
			global::C1.Android.Grid.Resource.Attribute.c1_typeface = global::FlexGrid101.Android.Resource.Attribute.c1_typeface;
			global::C1.Android.Grid.Resource.Id.all = global::FlexGrid101.Android.Resource.Id.all;
			global::C1.Android.Grid.Resource.Id.allHeaders = global::FlexGrid101.Android.Resource.Id.allHeaders;
			global::C1.Android.Grid.Resource.Id.bold = global::FlexGrid101.Android.Resource.Id.bold;
			global::C1.Android.Grid.Resource.Id.both = global::FlexGrid101.Android.Resource.Id.both;
			global::C1.Android.Grid.Resource.Id.cell = global::FlexGrid101.Android.Resource.Id.cell;
			global::C1.Android.Grid.Resource.Id.cellRange = global::FlexGrid101.Android.Resource.Id.cellRange;
			global::C1.Android.Grid.Resource.Id.cells = global::FlexGrid101.Android.Resource.Id.cells;
			global::C1.Android.Grid.Resource.Id.column = global::FlexGrid101.Android.Resource.Id.column;
			global::C1.Android.Grid.Resource.Id.columnHeaders = global::FlexGrid101.Android.Resource.Id.columnHeaders;
			global::C1.Android.Grid.Resource.Id.headers = global::FlexGrid101.Android.Resource.Id.headers;
			global::C1.Android.Grid.Resource.Id.horizontal = global::FlexGrid101.Android.Resource.Id.horizontal;
			global::C1.Android.Grid.Resource.Id.italic = global::FlexGrid101.Android.Resource.Id.italic;
			global::C1.Android.Grid.Resource.Id.monospace = global::FlexGrid101.Android.Resource.Id.monospace;
			global::C1.Android.Grid.Resource.Id.none = global::FlexGrid101.Android.Resource.Id.none;
			global::C1.Android.Grid.Resource.Id.normal = global::FlexGrid101.Android.Resource.Id.normal;
			global::C1.Android.Grid.Resource.Id.row = global::FlexGrid101.Android.Resource.Id.row;
			global::C1.Android.Grid.Resource.Id.rowHeaders = global::FlexGrid101.Android.Resource.Id.rowHeaders;
			global::C1.Android.Grid.Resource.Id.rowRange = global::FlexGrid101.Android.Resource.Id.rowRange;
			global::C1.Android.Grid.Resource.Id.sans = global::FlexGrid101.Android.Resource.Id.sans;
			global::C1.Android.Grid.Resource.Id.serif = global::FlexGrid101.Android.Resource.Id.serif;
			global::C1.Android.Grid.Resource.Id.vertical = global::FlexGrid101.Android.Resource.Id.vertical;
			global::C1.Android.Grid.Resource.String.ApplicationName = global::FlexGrid101.Android.Resource.String.ApplicationName;
			global::C1.Android.Grid.Resource.String.Hello = global::FlexGrid101.Android.Resource.String.Hello;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid = global::FlexGrid101.Android.Resource.Styleable.FlexGrid;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_allowMerging = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_allowMerging;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_alternatingRowBackgroundColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_alternatingRowBackgroundColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_autoGenerateColumns = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_autoGenerateColumns;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_autoSizeMode = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_autoSizeMode;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_backgroundColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_backgroundColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_borderColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_borderColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_columnHeaderBackgroundColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_columnHeaderBackgroundColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_columnHeaderSelectedBackgroundColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_columnHeaderSelectedBackgroundColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_columnHeaderTextColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_columnHeaderTextColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_cursorBackgroundColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_cursorBackgroundColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_cursorTextColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_cursorTextColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_defaultRowHeight = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_defaultRowHeight;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_editorBackgroundColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_editorBackgroundColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_editorTextColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_editorTextColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_fontFamily = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_fontFamily;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_frozenColumns = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_frozenColumns;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_frozenRows = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_frozenRows;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_gridLinesColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_gridLinesColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_gridLinesVisibility = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_gridLinesVisibility;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_gridSelectionMode = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_gridSelectionMode;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_headerGridLinesColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_headerGridLinesColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_headersGridLinesVisibility = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_headersGridLinesVisibility;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_headersVisibility = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_headersVisibility;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_isReadOnly = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_isReadOnly;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_rowBackgroundColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_rowBackgroundColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_rowHeaderBackgroundColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_rowHeaderBackgroundColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_rowHeaderSelectedBackgroundColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_rowHeaderSelectedBackgroundColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_rowHeaderTextColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_rowHeaderTextColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_selectionAdornerBorderColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_selectionAdornerBorderColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_selectionAdornerColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_selectionAdornerColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_selectionBackgroundColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_selectionBackgroundColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_selectionTextColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_selectionTextColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_showMarquee = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_showMarquee;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_showOutlineBar = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_showOutlineBar;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_textColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_textColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_textSize = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_textSize;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_textStyle = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_textStyle;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_topLeftCellBackgroundColor = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_topLeftCellBackgroundColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_typeface = global::FlexGrid101.Android.Resource.Styleable.FlexGrid_c1_typeface;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int c1_allowMerging = 2130771972;
			
			// aapt resource value: 0x7f01000e
			public const int c1_alternatingRowBackgroundColor = 2130771982;
			
			// aapt resource value: 0x7f01000a
			public const int c1_autoGenerateColumns = 2130771978;
			
			// aapt resource value: 0x7f010005
			public const int c1_autoSizeMode = 2130771973;
			
			// aapt resource value: 0x7f01001e
			public const int c1_backgroundColor = 2130771998;
			
			// aapt resource value: 0x7f010024
			public const int c1_borderColor = 2130772004;
			
			// aapt resource value: 0x7f01001a
			public const int c1_columnHeaderBackgroundColor = 2130771994;
			
			// aapt resource value: 0x7f010019
			public const int c1_columnHeaderSelectedBackgroundColor = 2130771993;
			
			// aapt resource value: 0x7f01001b
			public const int c1_columnHeaderTextColor = 2130771995;
			
			// aapt resource value: 0x7f01000f
			public const int c1_cursorBackgroundColor = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int c1_cursorTextColor = 2130771984;
			
			// aapt resource value: 0x7f010008
			public const int c1_defaultRowHeight = 2130771976;
			
			// aapt resource value: 0x7f010011
			public const int c1_editorBackgroundColor = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int c1_editorTextColor = 2130771986;
			
			// aapt resource value: 0x7f010022
			public const int c1_fontFamily = 2130772002;
			
			// aapt resource value: 0x7f010007
			public const int c1_frozenColumns = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int c1_frozenRows = 2130771974;
			
			// aapt resource value: 0x7f010017
			public const int c1_gridLinesColor = 2130771991;
			
			// aapt resource value: 0x7f010002
			public const int c1_gridLinesVisibility = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int c1_gridSelectionMode = 2130771968;
			
			// aapt resource value: 0x7f010018
			public const int c1_headerGridLinesColor = 2130771992;
			
			// aapt resource value: 0x7f010003
			public const int c1_headersGridLinesVisibility = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int c1_headersVisibility = 2130771969;
			
			// aapt resource value: 0x7f010009
			public const int c1_isReadOnly = 2130771977;
			
			// aapt resource value: 0x7f01000d
			public const int c1_rowBackgroundColor = 2130771981;
			
			// aapt resource value: 0x7f010014
			public const int c1_rowHeaderBackgroundColor = 2130771988;
			
			// aapt resource value: 0x7f010016
			public const int c1_rowHeaderSelectedBackgroundColor = 2130771990;
			
			// aapt resource value: 0x7f010015
			public const int c1_rowHeaderTextColor = 2130771989;
			
			// aapt resource value: 0x7f010027
			public const int c1_selectedIndex = 2130772007;
			
			// aapt resource value: 0x7f01001d
			public const int c1_selectionAdornerBorderColor = 2130771997;
			
			// aapt resource value: 0x7f01001c
			public const int c1_selectionAdornerColor = 2130771996;
			
			// aapt resource value: 0x7f010025
			public const int c1_selectionBackgroundColor = 2130772005;
			
			// aapt resource value: 0x7f010026
			public const int c1_selectionTextColor = 2130772006;
			
			// aapt resource value: 0x7f01000c
			public const int c1_showMarquee = 2130771980;
			
			// aapt resource value: 0x7f01000b
			public const int c1_showOutlineBar = 2130771979;
			
			// aapt resource value: 0x7f01001f
			public const int c1_textColor = 2130771999;
			
			// aapt resource value: 0x7f010020
			public const int c1_textSize = 2130772000;
			
			// aapt resource value: 0x7f010021
			public const int c1_textStyle = 2130772001;
			
			// aapt resource value: 0x7f010013
			public const int c1_topLeftCellBackgroundColor = 2130771987;
			
			// aapt resource value: 0x7f010023
			public const int c1_typeface = 2130772003;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_save = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_arrow_collapse = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_edit = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_fast_forward = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_filter = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_filter_remove = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_rewind = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_skip_next = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_skip_previous = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_sort_ascending = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_sort_descending = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Icon = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050015
			public const int MyButton = 2131034133;
			
			// aapt resource value: 0x7f050005
			public const int all = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int allHeaders = 2131034121;
			
			// aapt resource value: 0x7f05000f
			public const int bold = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int both = 2131034125;
			
			// aapt resource value: 0x7f050000
			public const int cell = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int cellRange = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int cells = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int column = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int columnHeaders = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int headers = 2131034126;
			
			// aapt resource value: 0x7f050007
			public const int horizontal = 2131034119;
			
			// aapt resource value: 0x7f050010
			public const int italic = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int monospace = 2131034130;
			
			// aapt resource value: 0x7f050002
			public const int none = 2131034114;
			
			// aapt resource value: 0x7f050011
			public const int normal = 2131034129;
			
			// aapt resource value: 0x7f050003
			public const int row = 2131034115;
			
			// aapt resource value: 0x7f05000c
			public const int rowHeaders = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int rowRange = 2131034116;
			
			// aapt resource value: 0x7f050013
			public const int sans = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int serif = 2131034132;
			
			// aapt resource value: 0x7f050008
			public const int vertical = 2131034120;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] C1Gauge = new int[] {
					2130771998};
			
			// aapt resource value: 0
			public const int C1Gauge_c1_backgroundColor = 0;
			
			public static int[] FlexGrid = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006};
			
			// aapt resource value: 4
			public const int FlexGrid_c1_allowMerging = 4;
			
			// aapt resource value: 14
			public const int FlexGrid_c1_alternatingRowBackgroundColor = 14;
			
			// aapt resource value: 10
			public const int FlexGrid_c1_autoGenerateColumns = 10;
			
			// aapt resource value: 5
			public const int FlexGrid_c1_autoSizeMode = 5;
			
			// aapt resource value: 30
			public const int FlexGrid_c1_backgroundColor = 30;
			
			// aapt resource value: 36
			public const int FlexGrid_c1_borderColor = 36;
			
			// aapt resource value: 26
			public const int FlexGrid_c1_columnHeaderBackgroundColor = 26;
			
			// aapt resource value: 25
			public const int FlexGrid_c1_columnHeaderSelectedBackgroundColor = 25;
			
			// aapt resource value: 27
			public const int FlexGrid_c1_columnHeaderTextColor = 27;
			
			// aapt resource value: 15
			public const int FlexGrid_c1_cursorBackgroundColor = 15;
			
			// aapt resource value: 16
			public const int FlexGrid_c1_cursorTextColor = 16;
			
			// aapt resource value: 8
			public const int FlexGrid_c1_defaultRowHeight = 8;
			
			// aapt resource value: 17
			public const int FlexGrid_c1_editorBackgroundColor = 17;
			
			// aapt resource value: 18
			public const int FlexGrid_c1_editorTextColor = 18;
			
			// aapt resource value: 34
			public const int FlexGrid_c1_fontFamily = 34;
			
			// aapt resource value: 7
			public const int FlexGrid_c1_frozenColumns = 7;
			
			// aapt resource value: 6
			public const int FlexGrid_c1_frozenRows = 6;
			
			// aapt resource value: 23
			public const int FlexGrid_c1_gridLinesColor = 23;
			
			// aapt resource value: 2
			public const int FlexGrid_c1_gridLinesVisibility = 2;
			
			// aapt resource value: 0
			public const int FlexGrid_c1_gridSelectionMode = 0;
			
			// aapt resource value: 24
			public const int FlexGrid_c1_headerGridLinesColor = 24;
			
			// aapt resource value: 3
			public const int FlexGrid_c1_headersGridLinesVisibility = 3;
			
			// aapt resource value: 1
			public const int FlexGrid_c1_headersVisibility = 1;
			
			// aapt resource value: 9
			public const int FlexGrid_c1_isReadOnly = 9;
			
			// aapt resource value: 13
			public const int FlexGrid_c1_rowBackgroundColor = 13;
			
			// aapt resource value: 20
			public const int FlexGrid_c1_rowHeaderBackgroundColor = 20;
			
			// aapt resource value: 22
			public const int FlexGrid_c1_rowHeaderSelectedBackgroundColor = 22;
			
			// aapt resource value: 21
			public const int FlexGrid_c1_rowHeaderTextColor = 21;
			
			// aapt resource value: 29
			public const int FlexGrid_c1_selectionAdornerBorderColor = 29;
			
			// aapt resource value: 28
			public const int FlexGrid_c1_selectionAdornerColor = 28;
			
			// aapt resource value: 37
			public const int FlexGrid_c1_selectionBackgroundColor = 37;
			
			// aapt resource value: 38
			public const int FlexGrid_c1_selectionTextColor = 38;
			
			// aapt resource value: 12
			public const int FlexGrid_c1_showMarquee = 12;
			
			// aapt resource value: 11
			public const int FlexGrid_c1_showOutlineBar = 11;
			
			// aapt resource value: 31
			public const int FlexGrid_c1_textColor = 31;
			
			// aapt resource value: 32
			public const int FlexGrid_c1_textSize = 32;
			
			// aapt resource value: 33
			public const int FlexGrid_c1_textStyle = 33;
			
			// aapt resource value: 19
			public const int FlexGrid_c1_topLeftCellBackgroundColor = 19;
			
			// aapt resource value: 35
			public const int FlexGrid_c1_typeface = 35;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
