#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FlexGrid101.Resource", IsApplication=true)]

namespace FlexGrid101
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::C1.Android.Core.Resource.Attribute.c1_backgroundColor = global::FlexGrid101.Resource.Attribute.c1_backgroundColor;
			global::C1.Android.Core.Resource.Attribute.c1_borderColor = global::FlexGrid101.Resource.Attribute.c1_borderColor;
			global::C1.Android.Core.Resource.Attribute.c1_fontFamily = global::FlexGrid101.Resource.Attribute.c1_fontFamily;
			global::C1.Android.Core.Resource.Attribute.c1_selectedIndex = global::FlexGrid101.Resource.Attribute.c1_selectedIndex;
			global::C1.Android.Core.Resource.Attribute.c1_selectionBackgroundColor = global::FlexGrid101.Resource.Attribute.c1_selectionBackgroundColor;
			global::C1.Android.Core.Resource.Attribute.c1_selectionTextColor = global::FlexGrid101.Resource.Attribute.c1_selectionTextColor;
			global::C1.Android.Core.Resource.Attribute.c1_textColor = global::FlexGrid101.Resource.Attribute.c1_textColor;
			global::C1.Android.Core.Resource.Attribute.c1_textSize = global::FlexGrid101.Resource.Attribute.c1_textSize;
			global::C1.Android.Core.Resource.Attribute.c1_textStyle = global::FlexGrid101.Resource.Attribute.c1_textStyle;
			global::C1.Android.Core.Resource.Attribute.c1_typeface = global::FlexGrid101.Resource.Attribute.c1_typeface;
			global::C1.Android.Core.Resource.Id.bold = global::FlexGrid101.Resource.Id.bold;
			global::C1.Android.Core.Resource.Id.italic = global::FlexGrid101.Resource.Id.italic;
			global::C1.Android.Core.Resource.Id.monospace = global::FlexGrid101.Resource.Id.monospace;
			global::C1.Android.Core.Resource.Id.normal = global::FlexGrid101.Resource.Id.normal;
			global::C1.Android.Core.Resource.Id.sans = global::FlexGrid101.Resource.Id.sans;
			global::C1.Android.Core.Resource.Id.serif = global::FlexGrid101.Resource.Id.serif;
			global::C1.Android.Gauge.Resource.Attribute.c1_backgroundColor = global::FlexGrid101.Resource.Attribute.c1_backgroundColor;
			global::C1.Android.Gauge.Resource.Attribute.c1_borderColor = global::FlexGrid101.Resource.Attribute.c1_borderColor;
			global::C1.Android.Gauge.Resource.Attribute.c1_fontFamily = global::FlexGrid101.Resource.Attribute.c1_fontFamily;
			global::C1.Android.Gauge.Resource.Attribute.c1_selectedIndex = global::FlexGrid101.Resource.Attribute.c1_selectedIndex;
			global::C1.Android.Gauge.Resource.Attribute.c1_selectionBackgroundColor = global::FlexGrid101.Resource.Attribute.c1_selectionBackgroundColor;
			global::C1.Android.Gauge.Resource.Attribute.c1_selectionTextColor = global::FlexGrid101.Resource.Attribute.c1_selectionTextColor;
			global::C1.Android.Gauge.Resource.Attribute.c1_textColor = global::FlexGrid101.Resource.Attribute.c1_textColor;
			global::C1.Android.Gauge.Resource.Attribute.c1_textSize = global::FlexGrid101.Resource.Attribute.c1_textSize;
			global::C1.Android.Gauge.Resource.Attribute.c1_textStyle = global::FlexGrid101.Resource.Attribute.c1_textStyle;
			global::C1.Android.Gauge.Resource.Attribute.c1_typeface = global::FlexGrid101.Resource.Attribute.c1_typeface;
			global::C1.Android.Gauge.Resource.Id.bold = global::FlexGrid101.Resource.Id.bold;
			global::C1.Android.Gauge.Resource.Id.italic = global::FlexGrid101.Resource.Id.italic;
			global::C1.Android.Gauge.Resource.Id.monospace = global::FlexGrid101.Resource.Id.monospace;
			global::C1.Android.Gauge.Resource.Id.normal = global::FlexGrid101.Resource.Id.normal;
			global::C1.Android.Gauge.Resource.Id.sans = global::FlexGrid101.Resource.Id.sans;
			global::C1.Android.Gauge.Resource.Id.serif = global::FlexGrid101.Resource.Id.serif;
			global::C1.Android.Gauge.Resource.Styleable.C1Gauge = global::FlexGrid101.Resource.Styleable.C1Gauge;
			global::C1.Android.Gauge.Resource.Styleable.C1Gauge_c1_backgroundColor = global::FlexGrid101.Resource.Styleable.C1Gauge_c1_backgroundColor;
			global::C1.Android.Grid.Resource.Attribute.c1_allowMerging = global::FlexGrid101.Resource.Attribute.c1_allowMerging;
			global::C1.Android.Grid.Resource.Attribute.c1_alternatingRowBackgroundColor = global::FlexGrid101.Resource.Attribute.c1_alternatingRowBackgroundColor;
			global::C1.Android.Grid.Resource.Attribute.c1_autoGenerateColumns = global::FlexGrid101.Resource.Attribute.c1_autoGenerateColumns;
			global::C1.Android.Grid.Resource.Attribute.c1_autoSizeMode = global::FlexGrid101.Resource.Attribute.c1_autoSizeMode;
			global::C1.Android.Grid.Resource.Attribute.c1_backgroundColor = global::FlexGrid101.Resource.Attribute.c1_backgroundColor;
			global::C1.Android.Grid.Resource.Attribute.c1_borderColor = global::FlexGrid101.Resource.Attribute.c1_borderColor;
			global::C1.Android.Grid.Resource.Attribute.c1_columnHeaderBackgroundColor = global::FlexGrid101.Resource.Attribute.c1_columnHeaderBackgroundColor;
			global::C1.Android.Grid.Resource.Attribute.c1_columnHeaderSelectedBackgroundColor = global::FlexGrid101.Resource.Attribute.c1_columnHeaderSelectedBackgroundColor;
			global::C1.Android.Grid.Resource.Attribute.c1_columnHeaderTextColor = global::FlexGrid101.Resource.Attribute.c1_columnHeaderTextColor;
			global::C1.Android.Grid.Resource.Attribute.c1_cursorBackgroundColor = global::FlexGrid101.Resource.Attribute.c1_cursorBackgroundColor;
			global::C1.Android.Grid.Resource.Attribute.c1_cursorTextColor = global::FlexGrid101.Resource.Attribute.c1_cursorTextColor;
			global::C1.Android.Grid.Resource.Attribute.c1_defaultRowHeight = global::FlexGrid101.Resource.Attribute.c1_defaultRowHeight;
			global::C1.Android.Grid.Resource.Attribute.c1_editorBackgroundColor = global::FlexGrid101.Resource.Attribute.c1_editorBackgroundColor;
			global::C1.Android.Grid.Resource.Attribute.c1_editorTextColor = global::FlexGrid101.Resource.Attribute.c1_editorTextColor;
			global::C1.Android.Grid.Resource.Attribute.c1_fontFamily = global::FlexGrid101.Resource.Attribute.c1_fontFamily;
			global::C1.Android.Grid.Resource.Attribute.c1_frozenColumns = global::FlexGrid101.Resource.Attribute.c1_frozenColumns;
			global::C1.Android.Grid.Resource.Attribute.c1_frozenRows = global::FlexGrid101.Resource.Attribute.c1_frozenRows;
			global::C1.Android.Grid.Resource.Attribute.c1_gridLinesColor = global::FlexGrid101.Resource.Attribute.c1_gridLinesColor;
			global::C1.Android.Grid.Resource.Attribute.c1_gridLinesVisibility = global::FlexGrid101.Resource.Attribute.c1_gridLinesVisibility;
			global::C1.Android.Grid.Resource.Attribute.c1_gridSelectionMode = global::FlexGrid101.Resource.Attribute.c1_gridSelectionMode;
			global::C1.Android.Grid.Resource.Attribute.c1_headerGridLinesColor = global::FlexGrid101.Resource.Attribute.c1_headerGridLinesColor;
			global::C1.Android.Grid.Resource.Attribute.c1_headersVisibility = global::FlexGrid101.Resource.Attribute.c1_headersVisibility;
			global::C1.Android.Grid.Resource.Attribute.c1_isReadOnly = global::FlexGrid101.Resource.Attribute.c1_isReadOnly;
			global::C1.Android.Grid.Resource.Attribute.c1_rowBackgroundColor = global::FlexGrid101.Resource.Attribute.c1_rowBackgroundColor;
			global::C1.Android.Grid.Resource.Attribute.c1_rowHeaderBackgroundColor = global::FlexGrid101.Resource.Attribute.c1_rowHeaderBackgroundColor;
			global::C1.Android.Grid.Resource.Attribute.c1_rowHeaderSelectedBackgroundColor = global::FlexGrid101.Resource.Attribute.c1_rowHeaderSelectedBackgroundColor;
			global::C1.Android.Grid.Resource.Attribute.c1_rowHeaderTextColor = global::FlexGrid101.Resource.Attribute.c1_rowHeaderTextColor;
			global::C1.Android.Grid.Resource.Attribute.c1_selectedIndex = global::FlexGrid101.Resource.Attribute.c1_selectedIndex;
			global::C1.Android.Grid.Resource.Attribute.c1_selectionAdornerBorderColor = global::FlexGrid101.Resource.Attribute.c1_selectionAdornerBorderColor;
			global::C1.Android.Grid.Resource.Attribute.c1_selectionAdornerColor = global::FlexGrid101.Resource.Attribute.c1_selectionAdornerColor;
			global::C1.Android.Grid.Resource.Attribute.c1_selectionBackgroundColor = global::FlexGrid101.Resource.Attribute.c1_selectionBackgroundColor;
			global::C1.Android.Grid.Resource.Attribute.c1_selectionTextColor = global::FlexGrid101.Resource.Attribute.c1_selectionTextColor;
			global::C1.Android.Grid.Resource.Attribute.c1_showMarquee = global::FlexGrid101.Resource.Attribute.c1_showMarquee;
			global::C1.Android.Grid.Resource.Attribute.c1_showOutlineBar = global::FlexGrid101.Resource.Attribute.c1_showOutlineBar;
			global::C1.Android.Grid.Resource.Attribute.c1_textColor = global::FlexGrid101.Resource.Attribute.c1_textColor;
			global::C1.Android.Grid.Resource.Attribute.c1_textSize = global::FlexGrid101.Resource.Attribute.c1_textSize;
			global::C1.Android.Grid.Resource.Attribute.c1_textStyle = global::FlexGrid101.Resource.Attribute.c1_textStyle;
			global::C1.Android.Grid.Resource.Attribute.c1_topLeftCellBackgroundColor = global::FlexGrid101.Resource.Attribute.c1_topLeftCellBackgroundColor;
			global::C1.Android.Grid.Resource.Attribute.c1_typeface = global::FlexGrid101.Resource.Attribute.c1_typeface;
			global::C1.Android.Grid.Resource.Id.all = global::FlexGrid101.Resource.Id.all;
			global::C1.Android.Grid.Resource.Id.allHeaders = global::FlexGrid101.Resource.Id.allHeaders;
			global::C1.Android.Grid.Resource.Id.bold = global::FlexGrid101.Resource.Id.bold;
			global::C1.Android.Grid.Resource.Id.both = global::FlexGrid101.Resource.Id.both;
			global::C1.Android.Grid.Resource.Id.cell = global::FlexGrid101.Resource.Id.cell;
			global::C1.Android.Grid.Resource.Id.cellRange = global::FlexGrid101.Resource.Id.cellRange;
			global::C1.Android.Grid.Resource.Id.cells = global::FlexGrid101.Resource.Id.cells;
			global::C1.Android.Grid.Resource.Id.column = global::FlexGrid101.Resource.Id.column;
			global::C1.Android.Grid.Resource.Id.columnHeaders = global::FlexGrid101.Resource.Id.columnHeaders;
			global::C1.Android.Grid.Resource.Id.headers = global::FlexGrid101.Resource.Id.headers;
			global::C1.Android.Grid.Resource.Id.horizontal = global::FlexGrid101.Resource.Id.horizontal;
			global::C1.Android.Grid.Resource.Id.italic = global::FlexGrid101.Resource.Id.italic;
			global::C1.Android.Grid.Resource.Id.monospace = global::FlexGrid101.Resource.Id.monospace;
			global::C1.Android.Grid.Resource.Id.none = global::FlexGrid101.Resource.Id.none;
			global::C1.Android.Grid.Resource.Id.normal = global::FlexGrid101.Resource.Id.normal;
			global::C1.Android.Grid.Resource.Id.row = global::FlexGrid101.Resource.Id.row;
			global::C1.Android.Grid.Resource.Id.rowHeaders = global::FlexGrid101.Resource.Id.rowHeaders;
			global::C1.Android.Grid.Resource.Id.rowRange = global::FlexGrid101.Resource.Id.rowRange;
			global::C1.Android.Grid.Resource.Id.sans = global::FlexGrid101.Resource.Id.sans;
			global::C1.Android.Grid.Resource.Id.serif = global::FlexGrid101.Resource.Id.serif;
			global::C1.Android.Grid.Resource.Id.vertical = global::FlexGrid101.Resource.Id.vertical;
			global::C1.Android.Grid.Resource.String.ApplicationName = global::FlexGrid101.Resource.String.ApplicationName;
			global::C1.Android.Grid.Resource.String.Hello = global::FlexGrid101.Resource.String.Hello;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid = global::FlexGrid101.Resource.Styleable.FlexGrid;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_allowMerging = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_allowMerging;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_alternatingRowBackgroundColor = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_alternatingRowBackgroundColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_autoGenerateColumns = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_autoGenerateColumns;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_autoSizeMode = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_autoSizeMode;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_borderColor = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_borderColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_columnHeaderBackgroundColor = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_columnHeaderBackgroundColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_columnHeaderSelectedBackgroundColor = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_columnHeaderSelectedBackgroundColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_columnHeaderTextColor = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_columnHeaderTextColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_cursorBackgroundColor = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_cursorBackgroundColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_cursorTextColor = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_cursorTextColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_defaultRowHeight = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_defaultRowHeight;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_editorBackgroundColor = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_editorBackgroundColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_editorTextColor = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_editorTextColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_fontFamily = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_fontFamily;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_frozenColumns = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_frozenColumns;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_frozenRows = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_frozenRows;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_gridLinesColor = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_gridLinesColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_gridLinesVisibility = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_gridLinesVisibility;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_gridSelectionMode = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_gridSelectionMode;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_headerGridLinesColor = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_headerGridLinesColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_headersVisibility = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_headersVisibility;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_isReadOnly = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_isReadOnly;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_rowBackgroundColor = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_rowBackgroundColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_rowHeaderBackgroundColor = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_rowHeaderBackgroundColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_rowHeaderSelectedBackgroundColor = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_rowHeaderSelectedBackgroundColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_rowHeaderTextColor = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_rowHeaderTextColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_selectionAdornerBorderColor = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_selectionAdornerBorderColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_selectionAdornerColor = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_selectionAdornerColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_selectionBackgroundColor = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_selectionBackgroundColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_selectionTextColor = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_selectionTextColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_showMarquee = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_showMarquee;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_showOutlineBar = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_showOutlineBar;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_textColor = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_textColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_textSize = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_textSize;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_textStyle = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_textStyle;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_topLeftCellBackgroundColor = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_topLeftCellBackgroundColor;
			global::C1.Android.Grid.Resource.Styleable.FlexGrid_c1_typeface = global::FlexGrid101.Resource.Styleable.FlexGrid_c1_typeface;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public const int c1_allowMerging = 2130771975;
			
			// aapt resource value: 0x7f010011
			public const int c1_alternatingRowBackgroundColor = 2130771985;
			
			// aapt resource value: 0x7f01000d
			public const int c1_autoGenerateColumns = 2130771981;
			
			// aapt resource value: 0x7f010008
			public const int c1_autoSizeMode = 2130771976;
			
			// aapt resource value: 0x7f010021
			public const int c1_backgroundColor = 2130772001;
			
			// aapt resource value: 0x7f010027
			public const int c1_borderColor = 2130772007;
			
			// aapt resource value: 0x7f01001d
			public const int c1_columnHeaderBackgroundColor = 2130771997;
			
			// aapt resource value: 0x7f01001c
			public const int c1_columnHeaderSelectedBackgroundColor = 2130771996;
			
			// aapt resource value: 0x7f01001e
			public const int c1_columnHeaderTextColor = 2130771998;
			
			// aapt resource value: 0x7f010012
			public const int c1_cursorBackgroundColor = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int c1_cursorTextColor = 2130771987;
			
			// aapt resource value: 0x7f01000b
			public const int c1_defaultRowHeight = 2130771979;
			
			// aapt resource value: 0x7f010014
			public const int c1_editorBackgroundColor = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int c1_editorTextColor = 2130771989;
			
			// aapt resource value: 0x7f010025
			public const int c1_fontFamily = 2130772005;
			
			// aapt resource value: 0x7f01000a
			public const int c1_frozenColumns = 2130771978;
			
			// aapt resource value: 0x7f010009
			public const int c1_frozenRows = 2130771977;
			
			// aapt resource value: 0x7f01001a
			public const int c1_gridLinesColor = 2130771994;
			
			// aapt resource value: 0x7f010006
			public const int c1_gridLinesVisibility = 2130771974;
			
			// aapt resource value: 0x7f010004
			public const int c1_gridSelectionMode = 2130771972;
			
			// aapt resource value: 0x7f01001b
			public const int c1_headerGridLinesColor = 2130771995;
			
			// aapt resource value: 0x7f010005
			public const int c1_headersVisibility = 2130771973;
			
			// aapt resource value: 0x7f01000c
			public const int c1_isReadOnly = 2130771980;
			
			// aapt resource value: 0x7f010010
			public const int c1_rowBackgroundColor = 2130771984;
			
			// aapt resource value: 0x7f010017
			public const int c1_rowHeaderBackgroundColor = 2130771991;
			
			// aapt resource value: 0x7f010019
			public const int c1_rowHeaderSelectedBackgroundColor = 2130771993;
			
			// aapt resource value: 0x7f010018
			public const int c1_rowHeaderTextColor = 2130771992;
			
			// aapt resource value: 0x7f01002a
			public const int c1_selectedIndex = 2130772010;
			
			// aapt resource value: 0x7f010020
			public const int c1_selectionAdornerBorderColor = 2130772000;
			
			// aapt resource value: 0x7f01001f
			public const int c1_selectionAdornerColor = 2130771999;
			
			// aapt resource value: 0x7f010028
			public const int c1_selectionBackgroundColor = 2130772008;
			
			// aapt resource value: 0x7f010029
			public const int c1_selectionTextColor = 2130772009;
			
			// aapt resource value: 0x7f01000f
			public const int c1_showMarquee = 2130771983;
			
			// aapt resource value: 0x7f01000e
			public const int c1_showOutlineBar = 2130771982;
			
			// aapt resource value: 0x7f010022
			public const int c1_textColor = 2130772002;
			
			// aapt resource value: 0x7f010023
			public const int c1_textSize = 2130772003;
			
			// aapt resource value: 0x7f010024
			public const int c1_textStyle = 2130772004;
			
			// aapt resource value: 0x7f010016
			public const int c1_topLeftCellBackgroundColor = 2130771990;
			
			// aapt resource value: 0x7f010026
			public const int c1_typeface = 2130772006;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int filter = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int flexgrid = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int flexgrid_columns = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int flexgrid_custom = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int flexgrid_filter = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int flexgrid_freezing = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int flexgrid_grouping = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int flexgrid_headers = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int flexgrid_loading = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int flexgrid_merging = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int flexgrid_rowdetails = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int flexgrid_selection = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_action_save = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_edit = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_filter = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_filter_remove = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Icon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int input_form = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int placeholder = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int retro_TV_filled_50_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int retro_TV_filled_50_light = 2130837524;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050030
			public const int AddressLabel = 2131034160;
			
			// aapt resource value: 0x7f05002f
			public const int CityLabel = 2131034159;
			
			// aapt resource value: 0x7f05002e
			public const int CountryLabel = 2131034158;
			
			// aapt resource value: 0x7f05002c
			public const int EmptyListLabel = 2131034156;
			
			// aapt resource value: 0x7f050024
			public const int Filter = 2131034148;
			
			// aapt resource value: 0x7f05001d
			public const int FirstName = 2131034141;
			
			// aapt resource value: 0x7f050016
			public const int Grid = 2131034134;
			
			// aapt resource value: 0x7f050025
			public const int Icon = 2131034149;
			
			// aapt resource value: 0x7f05001f
			public const int LastName = 2131034143;
			
			// aapt resource value: 0x7f050021
			public const int LastOrder = 2131034145;
			
			// aapt resource value: 0x7f050023
			public const int OrderTotal = 2131034147;
			
			// aapt resource value: 0x7f050031
			public const int PostalCodeLabel = 2131034161;
			
			// aapt resource value: 0x7f05002d
			public const int ProgressBar = 2131034157;
			
			// aapt resource value: 0x7f050029
			public const int RecyclerView = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int Search = 2131034154;
			
			// aapt resource value: 0x7f050033
			public const int SelectionTextView = 2131034163;
			
			// aapt resource value: 0x7f050019
			public const int ShowNameLabel = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int ShowTimeLabel = 2131034138;
			
			// aapt resource value: 0x7f050032
			public const int Spinner = 2131034162;
			
			// aapt resource value: 0x7f050028
			public const int Subtitle = 2131034152;
			
			// aapt resource value: 0x7f050027
			public const int Title = 2131034151;
			
			// aapt resource value: 0x7f050006
			public const int all = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int allHeaders = 2131034122;
			
			// aapt resource value: 0x7f050010
			public const int bold = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int both = 2131034126;
			
			// aapt resource value: 0x7f050001
			public const int cell = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int cellRange = 2131034114;
			
			// aapt resource value: 0x7f05000b
			public const int cells = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int column = 2131034119;
			
			// aapt resource value: 0x7f05000c
			public const int columnHeaders = 2131034124;
			
			// aapt resource value: 0x7f05001b
			public const int gridLayout1 = 2131034139;
			
			// aapt resource value: 0x7f05000f
			public const int headers = 2131034127;
			
			// aapt resource value: 0x7f050008
			public const int horizontal = 2131034120;
			
			// aapt resource value: 0x7f050018
			public const int imageView1 = 2131034136;
			
			// aapt resource value: 0x7f050011
			public const int italic = 2131034129;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f050017
			public const int linearLayout1 = 2131034135;
			
			// aapt resource value: 0x7f050013
			public const int monospace = 2131034131;
			
			// aapt resource value: 0x7f050003
			public const int none = 2131034115;
			
			// aapt resource value: 0x7f050012
			public const int normal = 2131034130;
			
			// aapt resource value: 0x7f05002b
			public const int relativeLayout1 = 2131034155;
			
			// aapt resource value: 0x7f050004
			public const int row = 2131034116;
			
			// aapt resource value: 0x7f05000d
			public const int rowHeaders = 2131034125;
			
			// aapt resource value: 0x7f050005
			public const int rowRange = 2131034117;
			
			// aapt resource value: 0x7f050014
			public const int sans = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int serif = 2131034133;
			
			// aapt resource value: 0x7f050022
			public const int textVie4 = 2131034146;
			
			// aapt resource value: 0x7f05001c
			public const int textView1 = 2131034140;
			
			// aapt resource value: 0x7f05001e
			public const int textView2 = 2131034142;
			
			// aapt resource value: 0x7f050020
			public const int textView3 = 2131034144;
			
			// aapt resource value: 0x7f050026
			public const int textview_container = 2131034150;
			
			// aapt resource value: 0x7f050009
			public const int vertical = 2131034121;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CellFreezing = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomAppearance = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CustomMerging = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EditingForm = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int FullTextFilter = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int GettingStarted = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ListItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int OnDemand = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int RowDetailsCell = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int SelectionModes = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f06002b
			public const int CellFreezingDescription = 2131099691;
			
			// aapt resource value: 0x7f06002a
			public const int CellFreezingTitle = 2131099690;
			
			// aapt resource value: 0x7f060036
			public const int CellsSelectedText = 2131099702;
			
			// aapt resource value: 0x7f060005
			public const int ColumnDefinitionDescription = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int ColumnDefinitionTitle = 2131099652;
			
			// aapt resource value: 0x7f060025
			public const int ColumnLayoutDescription = 2131099685;
			
			// aapt resource value: 0x7f060027
			public const int ColumnLayoutEdit = 2131099687;
			
			// aapt resource value: 0x7f060026
			public const int ColumnLayoutSave = 2131099686;
			
			// aapt resource value: 0x7f060024
			public const int ColumnLayoutTitle = 2131099684;
			
			// aapt resource value: 0x7f060014
			public const int ConditionalFormattingDescription = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int ConditionalFormattingTitle = 2131099667;
			
			// aapt resource value: 0x7f060033
			public const int CustomAppearanceDescription = 2131099699;
			
			// aapt resource value: 0x7f060032
			public const int CustomAppearanceTitle = 2131099698;
			
			// aapt resource value: 0x7f060016
			public const int CustomCellsDescription = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int CustomCellsTitle = 2131099669;
			
			// aapt resource value: 0x7f06002d
			public const int CustomMergingDescription = 2131099693;
			
			// aapt resource value: 0x7f06002c
			public const int CustomMergingTitle = 2131099692;
			
			// aapt resource value: 0x7f060009
			public const int EditConfirmationDescription = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int EditConfirmationQuestion = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int EditConfirmationQuestionTitle = 2131099659;
			
			// aapt resource value: 0x7f060008
			public const int EditConfirmationTitle = 2131099656;
			
			// aapt resource value: 0x7f06000d
			public const int EditingDescription = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int EditingFormFirstName = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int EditingFormLastName = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int EditingFormLastOrder = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int EditingFormOrderTotal = 2131099666;
			
			// aapt resource value: 0x7f06000e
			public const int EditingSelectRowMessage = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int EditingTitle = 2131099660;
			
			// aapt resource value: 0x7f060035
			public const int EmptyListText = 2131099701;
			
			// aapt resource value: 0x7f060020
			public const int FilterDescription = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int FilterPlaceholderText = 2131099681;
			
			// aapt resource value: 0x7f06001f
			public const int FilterTitle = 2131099679;
			
			// aapt resource value: 0x7f060023
			public const int FullTextFilterDescription = 2131099683;
			
			// aapt resource value: 0x7f060022
			public const int FullTextFilterTitle = 2131099682;
			
			// aapt resource value: 0x7f060003
			public const int GettingStartedDescription = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int GettingStartedTitle = 2131099650;
			
			// aapt resource value: 0x7f060018
			public const int GroupingDescription = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int GroupingTitle = 2131099671;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060031
			public const int OnDemandDescription = 2131099697;
			
			// aapt resource value: 0x7f060030
			public const int OnDemandTitle = 2131099696;
			
			// aapt resource value: 0x7f060037
			public const int RemoveFilter = 2131099703;
			
			// aapt resource value: 0x7f06001d
			public const int RowDetailsAddress = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int RowDetailsCity = 2131099676;
			
			// aapt resource value: 0x7f06001b
			public const int RowDetailsCountry = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int RowDetailsDescription = 2131099674;
			
			// aapt resource value: 0x7f06001e
			public const int RowDetailsPostalCode = 2131099678;
			
			// aapt resource value: 0x7f060019
			public const int RowDetailsTitle = 2131099673;
			
			// aapt resource value: 0x7f060034
			public const int SearchPlaceholderText = 2131099700;
			
			// aapt resource value: 0x7f060007
			public const int SelectionModesDescription = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int SelectionModesTitle = 2131099654;
			
			// aapt resource value: 0x7f060029
			public const int StarSizingDescription = 2131099689;
			
			// aapt resource value: 0x7f060028
			public const int StarSizingTitle = 2131099688;
			
			// aapt resource value: 0x7f06002f
			public const int UnboundDescription = 2131099695;
			
			// aapt resource value: 0x7f06002e
			public const int UnboundTitle = 2131099694;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] C1Gauge = new int[] {
					2130772001};
			
			// aapt resource value: 0
			public const int C1Gauge_c1_backgroundColor = 0;
			
			public static int[] FlexGrid = new int[] {
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009};
			
			// aapt resource value: 3
			public const int FlexGrid_c1_allowMerging = 3;
			
			// aapt resource value: 13
			public const int FlexGrid_c1_alternatingRowBackgroundColor = 13;
			
			// aapt resource value: 9
			public const int FlexGrid_c1_autoGenerateColumns = 9;
			
			// aapt resource value: 4
			public const int FlexGrid_c1_autoSizeMode = 4;
			
			// aapt resource value: 34
			public const int FlexGrid_c1_borderColor = 34;
			
			// aapt resource value: 25
			public const int FlexGrid_c1_columnHeaderBackgroundColor = 25;
			
			// aapt resource value: 24
			public const int FlexGrid_c1_columnHeaderSelectedBackgroundColor = 24;
			
			// aapt resource value: 26
			public const int FlexGrid_c1_columnHeaderTextColor = 26;
			
			// aapt resource value: 14
			public const int FlexGrid_c1_cursorBackgroundColor = 14;
			
			// aapt resource value: 15
			public const int FlexGrid_c1_cursorTextColor = 15;
			
			// aapt resource value: 7
			public const int FlexGrid_c1_defaultRowHeight = 7;
			
			// aapt resource value: 16
			public const int FlexGrid_c1_editorBackgroundColor = 16;
			
			// aapt resource value: 17
			public const int FlexGrid_c1_editorTextColor = 17;
			
			// aapt resource value: 32
			public const int FlexGrid_c1_fontFamily = 32;
			
			// aapt resource value: 6
			public const int FlexGrid_c1_frozenColumns = 6;
			
			// aapt resource value: 5
			public const int FlexGrid_c1_frozenRows = 5;
			
			// aapt resource value: 22
			public const int FlexGrid_c1_gridLinesColor = 22;
			
			// aapt resource value: 2
			public const int FlexGrid_c1_gridLinesVisibility = 2;
			
			// aapt resource value: 0
			public const int FlexGrid_c1_gridSelectionMode = 0;
			
			// aapt resource value: 23
			public const int FlexGrid_c1_headerGridLinesColor = 23;
			
			// aapt resource value: 1
			public const int FlexGrid_c1_headersVisibility = 1;
			
			// aapt resource value: 8
			public const int FlexGrid_c1_isReadOnly = 8;
			
			// aapt resource value: 12
			public const int FlexGrid_c1_rowBackgroundColor = 12;
			
			// aapt resource value: 19
			public const int FlexGrid_c1_rowHeaderBackgroundColor = 19;
			
			// aapt resource value: 21
			public const int FlexGrid_c1_rowHeaderSelectedBackgroundColor = 21;
			
			// aapt resource value: 20
			public const int FlexGrid_c1_rowHeaderTextColor = 20;
			
			// aapt resource value: 28
			public const int FlexGrid_c1_selectionAdornerBorderColor = 28;
			
			// aapt resource value: 27
			public const int FlexGrid_c1_selectionAdornerColor = 27;
			
			// aapt resource value: 35
			public const int FlexGrid_c1_selectionBackgroundColor = 35;
			
			// aapt resource value: 36
			public const int FlexGrid_c1_selectionTextColor = 36;
			
			// aapt resource value: 11
			public const int FlexGrid_c1_showMarquee = 11;
			
			// aapt resource value: 10
			public const int FlexGrid_c1_showOutlineBar = 10;
			
			// aapt resource value: 29
			public const int FlexGrid_c1_textColor = 29;
			
			// aapt resource value: 30
			public const int FlexGrid_c1_textSize = 30;
			
			// aapt resource value: 31
			public const int FlexGrid_c1_textStyle = 31;
			
			// aapt resource value: 18
			public const int FlexGrid_c1_topLeftCellBackgroundColor = 18;
			
			// aapt resource value: 33
			public const int FlexGrid_c1_typeface = 33;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
