// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using C1.iOS.Chart;

namespace Sunburst101
{
	public partial class BasicFeaturesController : UIViewController
	{
        
		public BasicFeaturesController (IntPtr handle) : base (handle)
		{
		}

		public BasicFeaturesController() : base("BasicFeaturesController", null)
        {
			
		}

		public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            // Perform any additional setup after loading the view, typically from a nib.

        	sunburst.Binding = "Value";
            sunburst.BindingName = "Year,Quarter,Month";
            sunburst.ChildItemsPath = "Items";
            sunburst.ToolTipContent = "{}{name}\n{y}";
            sunburst.DataLabel.Position = PieLabelPosition.Center;
            sunburst.DataLabel.Content = "{}{name}";
            sunburst.ItemsSource = new SunburstViewModel().HierarchicalData;
     	}

		partial void offsetChanged(UISlider sender)
		{
			sunburst.Offset = sender.Value;
		}

		partial void startAngleChanged(UISlider sender)
		{
			sunburst.StartAngle = sender.Value;
		}


		partial void switchValueChanged(UISwitch sender)
		{
			sunburst.Reversed = sender.On;
		}

		partial void valueChanged(UIStepper sender)
		{
			sunburst.InnerRadius = stepper.Value;
			innerRadiusLabel.Text = stepper.Value.ToString();
			innerRadiusLabel.SizeToFit();
		}
	}
}
