#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("C1CollectionView101.Resource", IsApplication=true)]

namespace C1CollectionView101
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int filter = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int grouping = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_sort_ascending = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_sort_descending = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int loading = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int placeholder = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int sort = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int Filter = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int Icon = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int RecyclerView = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int Search = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int Subtitle = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int SwipeRefresh = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int Title = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int textview_container = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Filtering = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int OnDemand = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SimpleOnDemand = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int ApplicationName = 2131099648;
			
			// aapt resource value: 0x7f06000c
			public const int FilterPlaceholderText = 2131099660;
			
			// aapt resource value: 0x7f060004
			public const int FilteringDescription = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int FilteringTitle = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int GroupingDescription = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int GroupingTitle = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int InternetConnectionError = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int OnDemandDescription = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int OnDemandTitle = 2131099657;
			
			// aapt resource value: 0x7f06000d
			public const int SearchPlaceholderText = 2131099661;
			
			// aapt resource value: 0x7f060008
			public const int SimpleOnDemandDescription = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int SimpleOnDemandTitle = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int SortingDescription = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int SortingTitle = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
