#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("C1CollectionView101.Resource", IsApplication=true)]

namespace C1CollectionView101
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int filter = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int grouping = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_sort_ascending = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_sort_descending = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int loading = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int placeholder = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int sort = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int Filter = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int Icon = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int RecyclerView = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int Search = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int Subtitle = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int SwipeRefresh = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int Title = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int textview_container = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Filtering = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int OnDemand = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SimpleOnDemand = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f04000c
			public const int FilterPlaceholderText = 2130968588;
			
			// aapt resource value: 0x7f040004
			public const int FilteringDescription = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int FilteringTitle = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int GroupingDescription = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int GroupingTitle = 2130968581;
			
			// aapt resource value: 0x7f04000b
			public const int InternetConnectionError = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int OnDemandDescription = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int OnDemandTitle = 2130968585;
			
			// aapt resource value: 0x7f04000d
			public const int SearchPlaceholderText = 2130968589;
			
			// aapt resource value: 0x7f040008
			public const int SimpleOnDemandDescription = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int SimpleOnDemandTitle = 2130968583;
			
			// aapt resource value: 0x7f040002
			public const int SortingDescription = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int SortingTitle = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
