// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using C1.Mac.CollectionView;
using C1.CollectionView;

namespace C1CollectionView101
{
	public partial class FilterViewController : NSViewController
	{
		public FilterViewController (IntPtr handle) : base (handle)
		{
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            TableView.SetItemsSource(Customer.GetCustomerList(1000));
			SearchField.Changed += OnSearchChanged;
        }

        public override void ViewDidDisappear()
        {
            base.ViewDidDisappear();
			SearchField.Changed -= OnSearchChanged;
		}

        private async void OnSearchChanged(object sender, EventArgs e)
        {
            var source= TableView.Source as C1TableViewSource;
            await source.CollectionView.FilterAsync(SearchField.StringValue);
        }
    }
}
