// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using C1.Mac.CollectionView;
using System.Threading.Tasks;
using C1.CollectionView;

namespace C1CollectionView101
{
    public partial class GroupingViewController : NSViewController
    {
        public GroupingViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            Load();
        }

        private async Task Load()
        {
            var source = new C1TableViewSource(TableView);
            source.ItemsSource = Customer.GetCustomerList(1000);
            await source.CollectionView.GroupAsync("Country");
            TableView.Source = source;
        }
    }
}
