#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("C1Calendar101.Resource", IsApplication=true)]

namespace C1Calendar101
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::C1.Android.Calendar.Resource.Attribute.c1_adjacentDayTextColor = global::C1Calendar101.Resource.Attribute.c1_adjacentDayTextColor;
			global::C1.Android.Calendar.Resource.Attribute.c1_backgroundColor = global::C1Calendar101.Resource.Attribute.c1_backgroundColor;
			global::C1.Android.Calendar.Resource.Attribute.c1_borderColor = global::C1Calendar101.Resource.Attribute.c1_borderColor;
			global::C1.Android.Calendar.Resource.Attribute.c1_calendarType = global::C1Calendar101.Resource.Attribute.c1_calendarType;
			global::C1.Android.Calendar.Resource.Attribute.c1_dayBorderColor = global::C1Calendar101.Resource.Attribute.c1_dayBorderColor;
			global::C1.Android.Calendar.Resource.Attribute.c1_dayBorderWidth = global::C1Calendar101.Resource.Attribute.c1_dayBorderWidth;
			global::C1.Android.Calendar.Resource.Attribute.c1_dayOfWeekBackgroundColor = global::C1Calendar101.Resource.Attribute.c1_dayOfWeekBackgroundColor;
			global::C1.Android.Calendar.Resource.Attribute.c1_dayOfWeekFontFamily = global::C1Calendar101.Resource.Attribute.c1_dayOfWeekFontFamily;
			global::C1.Android.Calendar.Resource.Attribute.c1_dayOfWeekFormat = global::C1Calendar101.Resource.Attribute.c1_dayOfWeekFormat;
			global::C1.Android.Calendar.Resource.Attribute.c1_dayOfWeekTextColor = global::C1Calendar101.Resource.Attribute.c1_dayOfWeekTextColor;
			global::C1.Android.Calendar.Resource.Attribute.c1_dayOfWeekTextSize = global::C1Calendar101.Resource.Attribute.c1_dayOfWeekTextSize;
			global::C1.Android.Calendar.Resource.Attribute.c1_dayOfWeekTextStyle = global::C1Calendar101.Resource.Attribute.c1_dayOfWeekTextStyle;
			global::C1.Android.Calendar.Resource.Attribute.c1_dayOfWeekTypeface = global::C1Calendar101.Resource.Attribute.c1_dayOfWeekTypeface;
			global::C1.Android.Calendar.Resource.Attribute.c1_disabledTextColor = global::C1Calendar101.Resource.Attribute.c1_disabledTextColor;
			global::C1.Android.Calendar.Resource.Attribute.c1_firstDayOfWeek = global::C1Calendar101.Resource.Attribute.c1_firstDayOfWeek;
			global::C1.Android.Calendar.Resource.Attribute.c1_fontFamily = global::C1Calendar101.Resource.Attribute.c1_fontFamily;
			global::C1.Android.Calendar.Resource.Attribute.c1_headerBackgroundColor = global::C1Calendar101.Resource.Attribute.c1_headerBackgroundColor;
			global::C1.Android.Calendar.Resource.Attribute.c1_headerFontFamily = global::C1Calendar101.Resource.Attribute.c1_headerFontFamily;
			global::C1.Android.Calendar.Resource.Attribute.c1_headerMonthFormat = global::C1Calendar101.Resource.Attribute.c1_headerMonthFormat;
			global::C1.Android.Calendar.Resource.Attribute.c1_headerTextColor = global::C1Calendar101.Resource.Attribute.c1_headerTextColor;
			global::C1.Android.Calendar.Resource.Attribute.c1_headerTextSize = global::C1Calendar101.Resource.Attribute.c1_headerTextSize;
			global::C1.Android.Calendar.Resource.Attribute.c1_headerTextStyle = global::C1Calendar101.Resource.Attribute.c1_headerTextStyle;
			global::C1.Android.Calendar.Resource.Attribute.c1_headerTypeface = global::C1Calendar101.Resource.Attribute.c1_headerTypeface;
			global::C1.Android.Calendar.Resource.Attribute.c1_isAnimated = global::C1Calendar101.Resource.Attribute.c1_isAnimated;
			global::C1.Android.Calendar.Resource.Attribute.c1_maxSelectionCount = global::C1Calendar101.Resource.Attribute.c1_maxSelectionCount;
			global::C1.Android.Calendar.Resource.Attribute.c1_orientation = global::C1Calendar101.Resource.Attribute.c1_orientation;
			global::C1.Android.Calendar.Resource.Attribute.c1_selectedIndex = global::C1Calendar101.Resource.Attribute.c1_selectedIndex;
			global::C1.Android.Calendar.Resource.Attribute.c1_selectionBackgroundColor = global::C1Calendar101.Resource.Attribute.c1_selectionBackgroundColor;
			global::C1.Android.Calendar.Resource.Attribute.c1_selectionTextColor = global::C1Calendar101.Resource.Attribute.c1_selectionTextColor;
			global::C1.Android.Calendar.Resource.Attribute.c1_showHeader = global::C1Calendar101.Resource.Attribute.c1_showHeader;
			global::C1.Android.Calendar.Resource.Attribute.c1_showNavigationButtons = global::C1Calendar101.Resource.Attribute.c1_showNavigationButtons;
			global::C1.Android.Calendar.Resource.Attribute.c1_textColor = global::C1Calendar101.Resource.Attribute.c1_textColor;
			global::C1.Android.Calendar.Resource.Attribute.c1_textSize = global::C1Calendar101.Resource.Attribute.c1_textSize;
			global::C1.Android.Calendar.Resource.Attribute.c1_textStyle = global::C1Calendar101.Resource.Attribute.c1_textStyle;
			global::C1.Android.Calendar.Resource.Attribute.c1_todayBackgroundColor = global::C1Calendar101.Resource.Attribute.c1_todayBackgroundColor;
			global::C1.Android.Calendar.Resource.Attribute.c1_todayFontFamily = global::C1Calendar101.Resource.Attribute.c1_todayFontFamily;
			global::C1.Android.Calendar.Resource.Attribute.c1_todayTextColor = global::C1Calendar101.Resource.Attribute.c1_todayTextColor;
			global::C1.Android.Calendar.Resource.Attribute.c1_todayTextStyle = global::C1Calendar101.Resource.Attribute.c1_todayTextStyle;
			global::C1.Android.Calendar.Resource.Attribute.c1_todayTypeface = global::C1Calendar101.Resource.Attribute.c1_todayTypeface;
			global::C1.Android.Calendar.Resource.Attribute.c1_typeface = global::C1Calendar101.Resource.Attribute.c1_typeface;
			global::C1.Android.Calendar.Resource.Attribute.c1_viewMode = global::C1Calendar101.Resource.Attribute.c1_viewMode;
			global::C1.Android.Calendar.Resource.Id.bold = global::C1Calendar101.Resource.Id.bold;
			global::C1.Android.Calendar.Resource.Id.decade = global::C1Calendar101.Resource.Id.decade;
			global::C1.Android.Calendar.Resource.Id.default_calendar = global::C1Calendar101.Resource.Id.default_calendar;
			global::C1.Android.Calendar.Resource.Id.friday = global::C1Calendar101.Resource.Id.friday;
			global::C1.Android.Calendar.Resource.Id.gregorian = global::C1Calendar101.Resource.Id.gregorian;
			global::C1.Android.Calendar.Resource.Id.horizontal = global::C1Calendar101.Resource.Id.horizontal;
			global::C1.Android.Calendar.Resource.Id.italic = global::C1Calendar101.Resource.Id.italic;
			global::C1.Android.Calendar.Resource.Id.japanese = global::C1Calendar101.Resource.Id.japanese;
			global::C1.Android.Calendar.Resource.Id.monday = global::C1Calendar101.Resource.Id.monday;
			global::C1.Android.Calendar.Resource.Id.monospace = global::C1Calendar101.Resource.Id.monospace;
			global::C1.Android.Calendar.Resource.Id.month = global::C1Calendar101.Resource.Id.month;
			global::C1.Android.Calendar.Resource.Id.normal = global::C1Calendar101.Resource.Id.normal;
			global::C1.Android.Calendar.Resource.Id.sans = global::C1Calendar101.Resource.Id.sans;
			global::C1.Android.Calendar.Resource.Id.saturday = global::C1Calendar101.Resource.Id.saturday;
			global::C1.Android.Calendar.Resource.Id.serif = global::C1Calendar101.Resource.Id.serif;
			global::C1.Android.Calendar.Resource.Id.sunday = global::C1Calendar101.Resource.Id.sunday;
			global::C1.Android.Calendar.Resource.Id.thursday = global::C1Calendar101.Resource.Id.thursday;
			global::C1.Android.Calendar.Resource.Id.tuesday = global::C1Calendar101.Resource.Id.tuesday;
			global::C1.Android.Calendar.Resource.Id.vertical = global::C1Calendar101.Resource.Id.vertical;
			global::C1.Android.Calendar.Resource.Id.wednesday = global::C1Calendar101.Resource.Id.wednesday;
			global::C1.Android.Calendar.Resource.Id.year = global::C1Calendar101.Resource.Id.year;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar = global::C1Calendar101.Resource.Styleable.C1Calendar;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_adjacentDayTextColor = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_adjacentDayTextColor;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_backgroundColor = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_backgroundColor;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_borderColor = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_borderColor;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_calendarType = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_calendarType;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_dayBorderColor = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_dayBorderColor;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_dayBorderWidth = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_dayBorderWidth;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_dayOfWeekBackgroundColor = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_dayOfWeekBackgroundColor;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_dayOfWeekFontFamily = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_dayOfWeekFontFamily;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_dayOfWeekFormat = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_dayOfWeekFormat;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_dayOfWeekTextColor = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_dayOfWeekTextColor;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_dayOfWeekTextSize = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_dayOfWeekTextSize;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_dayOfWeekTextStyle = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_dayOfWeekTextStyle;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_dayOfWeekTypeface = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_dayOfWeekTypeface;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_disabledTextColor = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_disabledTextColor;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_firstDayOfWeek = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_firstDayOfWeek;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_fontFamily = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_fontFamily;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_headerBackgroundColor = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_headerBackgroundColor;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_headerFontFamily = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_headerFontFamily;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_headerMonthFormat = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_headerMonthFormat;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_headerTextColor = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_headerTextColor;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_headerTextSize = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_headerTextSize;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_headerTextStyle = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_headerTextStyle;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_headerTypeface = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_headerTypeface;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_isAnimated = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_isAnimated;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_maxSelectionCount = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_maxSelectionCount;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_orientation = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_orientation;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_selectionBackgroundColor = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_selectionBackgroundColor;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_selectionTextColor = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_selectionTextColor;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_showHeader = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_showHeader;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_showNavigationButtons = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_showNavigationButtons;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_textColor = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_textColor;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_textSize = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_textSize;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_textStyle = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_textStyle;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_todayBackgroundColor = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_todayBackgroundColor;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_todayFontFamily = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_todayFontFamily;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_todayTextColor = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_todayTextColor;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_todayTextStyle = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_todayTextStyle;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_todayTypeface = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_todayTypeface;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_typeface = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_typeface;
			global::C1.Android.Calendar.Resource.Styleable.C1Calendar_c1_viewMode = global::C1Calendar101.Resource.Styleable.C1Calendar_c1_viewMode;
			global::C1.Android.Core.Resource.Attribute.c1_backgroundColor = global::C1Calendar101.Resource.Attribute.c1_backgroundColor;
			global::C1.Android.Core.Resource.Attribute.c1_borderColor = global::C1Calendar101.Resource.Attribute.c1_borderColor;
			global::C1.Android.Core.Resource.Attribute.c1_fontFamily = global::C1Calendar101.Resource.Attribute.c1_fontFamily;
			global::C1.Android.Core.Resource.Attribute.c1_selectedIndex = global::C1Calendar101.Resource.Attribute.c1_selectedIndex;
			global::C1.Android.Core.Resource.Attribute.c1_selectionBackgroundColor = global::C1Calendar101.Resource.Attribute.c1_selectionBackgroundColor;
			global::C1.Android.Core.Resource.Attribute.c1_selectionTextColor = global::C1Calendar101.Resource.Attribute.c1_selectionTextColor;
			global::C1.Android.Core.Resource.Attribute.c1_textColor = global::C1Calendar101.Resource.Attribute.c1_textColor;
			global::C1.Android.Core.Resource.Attribute.c1_textSize = global::C1Calendar101.Resource.Attribute.c1_textSize;
			global::C1.Android.Core.Resource.Attribute.c1_textStyle = global::C1Calendar101.Resource.Attribute.c1_textStyle;
			global::C1.Android.Core.Resource.Attribute.c1_typeface = global::C1Calendar101.Resource.Attribute.c1_typeface;
			global::C1.Android.Core.Resource.Id.bold = global::C1Calendar101.Resource.Id.bold;
			global::C1.Android.Core.Resource.Id.italic = global::C1Calendar101.Resource.Id.italic;
			global::C1.Android.Core.Resource.Id.monospace = global::C1Calendar101.Resource.Id.monospace;
			global::C1.Android.Core.Resource.Id.normal = global::C1Calendar101.Resource.Id.normal;
			global::C1.Android.Core.Resource.Id.sans = global::C1Calendar101.Resource.Id.sans;
			global::C1.Android.Core.Resource.Id.serif = global::C1Calendar101.Resource.Id.serif;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int viewModeSpinnerValues = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000e
			public const int c1_adjacentDayTextColor = 2130771982;
			
			// aapt resource value: 0x7f010004
			public const int c1_backgroundColor = 2130771972;
			
			// aapt resource value: 0x7f01000a
			public const int c1_borderColor = 2130771978;
			
			// aapt resource value: 0x7f010019
			public const int c1_calendarType = 2130771993;
			
			// aapt resource value: 0x7f01000f
			public const int c1_dayBorderColor = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int c1_dayBorderWidth = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int c1_dayOfWeekBackgroundColor = 2130771985;
			
			// aapt resource value: 0x7f010016
			public const int c1_dayOfWeekFontFamily = 2130771990;
			
			// aapt resource value: 0x7f010013
			public const int c1_dayOfWeekFormat = 2130771987;
			
			// aapt resource value: 0x7f010012
			public const int c1_dayOfWeekTextColor = 2130771986;
			
			// aapt resource value: 0x7f010014
			public const int c1_dayOfWeekTextSize = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int c1_dayOfWeekTextStyle = 2130771989;
			
			// aapt resource value: 0x7f010017
			public const int c1_dayOfWeekTypeface = 2130771991;
			
			// aapt resource value: 0x7f01002c
			public const int c1_disabledTextColor = 2130772012;
			
			// aapt resource value: 0x7f01001a
			public const int c1_firstDayOfWeek = 2130771994;
			
			// aapt resource value: 0x7f010008
			public const int c1_fontFamily = 2130771976;
			
			// aapt resource value: 0x7f01001c
			public const int c1_headerBackgroundColor = 2130771996;
			
			// aapt resource value: 0x7f010020
			public const int c1_headerFontFamily = 2130772000;
			
			// aapt resource value: 0x7f01001b
			public const int c1_headerMonthFormat = 2130771995;
			
			// aapt resource value: 0x7f01001d
			public const int c1_headerTextColor = 2130771997;
			
			// aapt resource value: 0x7f01001e
			public const int c1_headerTextSize = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int c1_headerTextStyle = 2130771999;
			
			// aapt resource value: 0x7f010021
			public const int c1_headerTypeface = 2130772001;
			
			// aapt resource value: 0x7f010022
			public const int c1_isAnimated = 2130772002;
			
			// aapt resource value: 0x7f010023
			public const int c1_maxSelectionCount = 2130772003;
			
			// aapt resource value: 0x7f010024
			public const int c1_orientation = 2130772004;
			
			// aapt resource value: 0x7f01000d
			public const int c1_selectedIndex = 2130771981;
			
			// aapt resource value: 0x7f01000b
			public const int c1_selectionBackgroundColor = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int c1_selectionTextColor = 2130771980;
			
			// aapt resource value: 0x7f010025
			public const int c1_showHeader = 2130772005;
			
			// aapt resource value: 0x7f010026
			public const int c1_showNavigationButtons = 2130772006;
			
			// aapt resource value: 0x7f010005
			public const int c1_textColor = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int c1_textSize = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int c1_textStyle = 2130771975;
			
			// aapt resource value: 0x7f010027
			public const int c1_todayBackgroundColor = 2130772007;
			
			// aapt resource value: 0x7f01002a
			public const int c1_todayFontFamily = 2130772010;
			
			// aapt resource value: 0x7f010028
			public const int c1_todayTextColor = 2130772008;
			
			// aapt resource value: 0x7f010029
			public const int c1_todayTextStyle = 2130772009;
			
			// aapt resource value: 0x7f01002b
			public const int c1_todayTypeface = 2130772011;
			
			// aapt resource value: 0x7f010009
			public const int c1_typeface = 2130771977;
			
			// aapt resource value: 0x7f010018
			public const int c1_viewMode = 2130771992;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int calendar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int calendar2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int calendar_datepicker = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int calendar_vertical = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Cloudy = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int PartlyCloudy = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Rain = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Storm = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Sun = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050016
			public const int Calendar = 2131034134;
			
			// aapt resource value: 0x7f05001d
			public const int Day = 2131034141;
			
			// aapt resource value: 0x7f05001f
			public const int Icon = 2131034143;
			
			// aapt resource value: 0x7f05001e
			public const int Image = 2131034142;
			
			// aapt resource value: 0x7f050025
			public const int Message = 2131034149;
			
			// aapt resource value: 0x7f050019
			public const int MonthLabel = 2131034137;
			
			// aapt resource value: 0x7f050024
			public const int PickDateButton = 2131034148;
			
			// aapt resource value: 0x7f050023
			public const int RecyclerView = 2131034147;
			
			// aapt resource value: 0x7f050022
			public const int Subtitle = 2131034146;
			
			// aapt resource value: 0x7f050021
			public const int Title = 2131034145;
			
			// aapt resource value: 0x7f050018
			public const int TodayButton = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int ViewModeSpinner = 2131034135;
			
			// aapt resource value: 0x7f050001
			public const int bold = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int decade = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int default_calendar = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int friday = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int gregorian = 2131034123;
			
			// aapt resource value: 0x7f050014
			public const int horizontal = 2131034132;
			
			// aapt resource value: 0x7f050002
			public const int italic = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int japanese = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int monday = 2131034126;
			
			// aapt resource value: 0x7f050004
			public const int monospace = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int month = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int normal = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int sans = 2131034117;
			
			// aapt resource value: 0x7f05000f
			public const int saturday = 2131034127;
			
			// aapt resource value: 0x7f050006
			public const int serif = 2131034118;
			
			// aapt resource value: 0x7f050010
			public const int sunday = 2131034128;
			
			// aapt resource value: 0x7f05001a
			public const int textView1 = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int textView2 = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int textView3 = 2131034140;
			
			// aapt resource value: 0x7f050020
			public const int textview_container = 2131034144;
			
			// aapt resource value: 0x7f050011
			public const int thursday = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int tuesday = 2131034130;
			
			// aapt resource value: 0x7f050015
			public const int vertical = 2131034133;
			
			// aapt resource value: 0x7f050013
			public const int wednesday = 2131034131;
			
			// aapt resource value: 0x7f050009
			public const int year = 2131034121;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomAppearance = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomDayContent = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CustomHeader = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CustomSelection = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DaySlot = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int GettingStarted = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ListItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int PopupEditor = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int VerticalOrientation = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int ApplicationName = 2131099648;
			
			// aapt resource value: 0x7f060016
			public const int customSelectionGuide_observe = 2131099670;
			
			// aapt resource value: 0x7f060014
			public const int customSelectionGuide_step1 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int customSelectionGuide_step2 = 2131099669;
			
			// aapt resource value: 0x7f06000b
			public const int custom_appearance = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int custom_appearance_desc = 2131099660;
			
			// aapt resource value: 0x7f060005
			public const int custom_day_content = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int custom_day_content_desc = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int custom_header = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int custom_header_desc = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int custom_header_text = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int custom_header_text_desc = 2131099658;
			
			// aapt resource value: 0x7f06000f
			public const int custom_selection = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int custom_selection_desc = 2131099664;
			
			// aapt resource value: 0x7f060001
			public const int getting_started = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int getting_started_desc = 2131099650;
			
			// aapt resource value: 0x7f06000d
			public const int popup_editor = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int popup_editor_desc = 2131099662;
			
			// aapt resource value: 0x7f060012
			public const int selectDate = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int showSelectedDate = 2131099667;
			
			// aapt resource value: 0x7f060011
			public const int today = 2131099665;
			
			// aapt resource value: 0x7f060003
			public const int vertical_orientation = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int vertical_orientation_desc = 2131099652;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] C1Calendar = new int[] {
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012};
			
			// aapt resource value: 9
			public const int C1Calendar_c1_adjacentDayTextColor = 9;
			
			// aapt resource value: 0
			public const int C1Calendar_c1_backgroundColor = 0;
			
			// aapt resource value: 6
			public const int C1Calendar_c1_borderColor = 6;
			
			// aapt resource value: 20
			public const int C1Calendar_c1_calendarType = 20;
			
			// aapt resource value: 10
			public const int C1Calendar_c1_dayBorderColor = 10;
			
			// aapt resource value: 11
			public const int C1Calendar_c1_dayBorderWidth = 11;
			
			// aapt resource value: 12
			public const int C1Calendar_c1_dayOfWeekBackgroundColor = 12;
			
			// aapt resource value: 17
			public const int C1Calendar_c1_dayOfWeekFontFamily = 17;
			
			// aapt resource value: 14
			public const int C1Calendar_c1_dayOfWeekFormat = 14;
			
			// aapt resource value: 13
			public const int C1Calendar_c1_dayOfWeekTextColor = 13;
			
			// aapt resource value: 15
			public const int C1Calendar_c1_dayOfWeekTextSize = 15;
			
			// aapt resource value: 16
			public const int C1Calendar_c1_dayOfWeekTextStyle = 16;
			
			// aapt resource value: 18
			public const int C1Calendar_c1_dayOfWeekTypeface = 18;
			
			// aapt resource value: 39
			public const int C1Calendar_c1_disabledTextColor = 39;
			
			// aapt resource value: 21
			public const int C1Calendar_c1_firstDayOfWeek = 21;
			
			// aapt resource value: 4
			public const int C1Calendar_c1_fontFamily = 4;
			
			// aapt resource value: 23
			public const int C1Calendar_c1_headerBackgroundColor = 23;
			
			// aapt resource value: 27
			public const int C1Calendar_c1_headerFontFamily = 27;
			
			// aapt resource value: 22
			public const int C1Calendar_c1_headerMonthFormat = 22;
			
			// aapt resource value: 24
			public const int C1Calendar_c1_headerTextColor = 24;
			
			// aapt resource value: 25
			public const int C1Calendar_c1_headerTextSize = 25;
			
			// aapt resource value: 26
			public const int C1Calendar_c1_headerTextStyle = 26;
			
			// aapt resource value: 28
			public const int C1Calendar_c1_headerTypeface = 28;
			
			// aapt resource value: 29
			public const int C1Calendar_c1_isAnimated = 29;
			
			// aapt resource value: 30
			public const int C1Calendar_c1_maxSelectionCount = 30;
			
			// aapt resource value: 31
			public const int C1Calendar_c1_orientation = 31;
			
			// aapt resource value: 7
			public const int C1Calendar_c1_selectionBackgroundColor = 7;
			
			// aapt resource value: 8
			public const int C1Calendar_c1_selectionTextColor = 8;
			
			// aapt resource value: 32
			public const int C1Calendar_c1_showHeader = 32;
			
			// aapt resource value: 33
			public const int C1Calendar_c1_showNavigationButtons = 33;
			
			// aapt resource value: 1
			public const int C1Calendar_c1_textColor = 1;
			
			// aapt resource value: 2
			public const int C1Calendar_c1_textSize = 2;
			
			// aapt resource value: 3
			public const int C1Calendar_c1_textStyle = 3;
			
			// aapt resource value: 34
			public const int C1Calendar_c1_todayBackgroundColor = 34;
			
			// aapt resource value: 37
			public const int C1Calendar_c1_todayFontFamily = 37;
			
			// aapt resource value: 35
			public const int C1Calendar_c1_todayTextColor = 35;
			
			// aapt resource value: 36
			public const int C1Calendar_c1_todayTextStyle = 36;
			
			// aapt resource value: 38
			public const int C1Calendar_c1_todayTypeface = 38;
			
			// aapt resource value: 5
			public const int C1Calendar_c1_typeface = 5;
			
			// aapt resource value: 19
			public const int C1Calendar_c1_viewMode = 19;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
