#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sunburst101.Resource", IsApplication=true)]

namespace Sunburst101
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_format = global::Sunburst101.Resource.Attribute.c1_axisX_format;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_labelAlignment = global::Sunburst101.Resource.Attribute.c1_axisX_labelAlignment;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_labelAngle = global::Sunburst101.Resource.Attribute.c1_axisX_labelAngle;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_labelsVisible = global::Sunburst101.Resource.Attribute.c1_axisX_labelsVisible;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_line = global::Sunburst101.Resource.Attribute.c1_axisX_line;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_logBase = global::Sunburst101.Resource.Attribute.c1_axisX_logBase;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_majorGridStyleStroke = global::Sunburst101.Resource.Attribute.c1_axisX_majorGridStyleStroke;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_majorGridStyleStrokeThickness = global::Sunburst101.Resource.Attribute.c1_axisX_majorGridStyleStrokeThickness;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_majorGridVisible = global::Sunburst101.Resource.Attribute.c1_axisX_majorGridVisible;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_majorTickMark = global::Sunburst101.Resource.Attribute.c1_axisX_majorTickMark;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_majorUnit = global::Sunburst101.Resource.Attribute.c1_axisX_majorUnit;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_max = global::Sunburst101.Resource.Attribute.c1_axisX_max;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_min = global::Sunburst101.Resource.Attribute.c1_axisX_min;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_minorGridStyleStroke = global::Sunburst101.Resource.Attribute.c1_axisX_minorGridStyleStroke;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_minorGridStyleStrokeThickness = global::Sunburst101.Resource.Attribute.c1_axisX_minorGridStyleStrokeThickness;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_minorGridVisible = global::Sunburst101.Resource.Attribute.c1_axisX_minorGridVisible;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_minorTickMark = global::Sunburst101.Resource.Attribute.c1_axisX_minorTickMark;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_minorUnit = global::Sunburst101.Resource.Attribute.c1_axisX_minorUnit;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_origin = global::Sunburst101.Resource.Attribute.c1_axisX_origin;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_overlappingLabels = global::Sunburst101.Resource.Attribute.c1_axisX_overlappingLabels;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_position = global::Sunburst101.Resource.Attribute.c1_axisX_position;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_reversed = global::Sunburst101.Resource.Attribute.c1_axisX_reversed;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_styleFill = global::Sunburst101.Resource.Attribute.c1_axisX_styleFill;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_styleFontSize = global::Sunburst101.Resource.Attribute.c1_axisX_styleFontSize;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_styleStroke = global::Sunburst101.Resource.Attribute.c1_axisX_styleStroke;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_styleStrokeThickness = global::Sunburst101.Resource.Attribute.c1_axisX_styleStrokeThickness;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_styleTypeface = global::Sunburst101.Resource.Attribute.c1_axisX_styleTypeface;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_styleTypefaceStyle = global::Sunburst101.Resource.Attribute.c1_axisX_styleTypefaceStyle;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_title = global::Sunburst101.Resource.Attribute.c1_axisX_title;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_titleStyleFill = global::Sunburst101.Resource.Attribute.c1_axisX_titleStyleFill;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_titleStyleFontSize = global::Sunburst101.Resource.Attribute.c1_axisX_titleStyleFontSize;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_titleStyleStroke = global::Sunburst101.Resource.Attribute.c1_axisX_titleStyleStroke;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_titleStyleStrokeThickness = global::Sunburst101.Resource.Attribute.c1_axisX_titleStyleStrokeThickness;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_titleStyleTypeface = global::Sunburst101.Resource.Attribute.c1_axisX_titleStyleTypeface;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_titleStyleTypefaceStyle = global::Sunburst101.Resource.Attribute.c1_axisX_titleStyleTypefaceStyle;
			global::C1.Android.Chart.Resource.Attribute.c1_axisX_type = global::Sunburst101.Resource.Attribute.c1_axisX_type;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_format = global::Sunburst101.Resource.Attribute.c1_axisY_format;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_labelAlignment = global::Sunburst101.Resource.Attribute.c1_axisY_labelAlignment;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_labelAngle = global::Sunburst101.Resource.Attribute.c1_axisY_labelAngle;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_labelsVisible = global::Sunburst101.Resource.Attribute.c1_axisY_labelsVisible;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_line = global::Sunburst101.Resource.Attribute.c1_axisY_line;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_logBase = global::Sunburst101.Resource.Attribute.c1_axisY_logBase;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_majorGridStyleStroke = global::Sunburst101.Resource.Attribute.c1_axisY_majorGridStyleStroke;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_majorGridStyleStrokeThickness = global::Sunburst101.Resource.Attribute.c1_axisY_majorGridStyleStrokeThickness;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_majorGridVisible = global::Sunburst101.Resource.Attribute.c1_axisY_majorGridVisible;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_majorTickMark = global::Sunburst101.Resource.Attribute.c1_axisY_majorTickMark;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_majorUnit = global::Sunburst101.Resource.Attribute.c1_axisY_majorUnit;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_max = global::Sunburst101.Resource.Attribute.c1_axisY_max;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_min = global::Sunburst101.Resource.Attribute.c1_axisY_min;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_minorGridStyleStroke = global::Sunburst101.Resource.Attribute.c1_axisY_minorGridStyleStroke;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_minorGridStyleStrokeThickness = global::Sunburst101.Resource.Attribute.c1_axisY_minorGridStyleStrokeThickness;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_minorGridVisible = global::Sunburst101.Resource.Attribute.c1_axisY_minorGridVisible;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_minorTickMark = global::Sunburst101.Resource.Attribute.c1_axisY_minorTickMark;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_minorUnit = global::Sunburst101.Resource.Attribute.c1_axisY_minorUnit;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_origin = global::Sunburst101.Resource.Attribute.c1_axisY_origin;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_overlappingLabels = global::Sunburst101.Resource.Attribute.c1_axisY_overlappingLabels;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_position = global::Sunburst101.Resource.Attribute.c1_axisY_position;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_reversed = global::Sunburst101.Resource.Attribute.c1_axisY_reversed;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_styleFill = global::Sunburst101.Resource.Attribute.c1_axisY_styleFill;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_styleFontSize = global::Sunburst101.Resource.Attribute.c1_axisY_styleFontSize;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_styleStroke = global::Sunburst101.Resource.Attribute.c1_axisY_styleStroke;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_styleStrokeThickness = global::Sunburst101.Resource.Attribute.c1_axisY_styleStrokeThickness;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_styleTypeface = global::Sunburst101.Resource.Attribute.c1_axisY_styleTypeface;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_styleTypefaceStyle = global::Sunburst101.Resource.Attribute.c1_axisY_styleTypefaceStyle;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_title = global::Sunburst101.Resource.Attribute.c1_axisY_title;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_titleStyleFill = global::Sunburst101.Resource.Attribute.c1_axisY_titleStyleFill;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_titleStyleFontSize = global::Sunburst101.Resource.Attribute.c1_axisY_titleStyleFontSize;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_titleStyleStroke = global::Sunburst101.Resource.Attribute.c1_axisY_titleStyleStroke;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_titleStyleStrokeThickness = global::Sunburst101.Resource.Attribute.c1_axisY_titleStyleStrokeThickness;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_titleStyleTypeface = global::Sunburst101.Resource.Attribute.c1_axisY_titleStyleTypeface;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_titleStyleTypefaceStyle = global::Sunburst101.Resource.Attribute.c1_axisY_titleStyleTypefaceStyle;
			global::C1.Android.Chart.Resource.Attribute.c1_axisY_type = global::Sunburst101.Resource.Attribute.c1_axisY_type;
			global::C1.Android.Chart.Resource.Attribute.c1_backgroundColor = global::Sunburst101.Resource.Attribute.c1_backgroundColor;
			global::C1.Android.Chart.Resource.Attribute.c1_binding = global::Sunburst101.Resource.Attribute.c1_binding;
			global::C1.Android.Chart.Resource.Attribute.c1_bindingName = global::Sunburst101.Resource.Attribute.c1_bindingName;
			global::C1.Android.Chart.Resource.Attribute.c1_bindingX = global::Sunburst101.Resource.Attribute.c1_bindingX;
			global::C1.Android.Chart.Resource.Attribute.c1_borderColor = global::Sunburst101.Resource.Attribute.c1_borderColor;
			global::C1.Android.Chart.Resource.Attribute.c1_chartType = global::Sunburst101.Resource.Attribute.c1_chartType;
			global::C1.Android.Chart.Resource.Attribute.c1_childItemsPath = global::Sunburst101.Resource.Attribute.c1_childItemsPath;
			global::C1.Android.Chart.Resource.Attribute.c1_datalabel_border = global::Sunburst101.Resource.Attribute.c1_datalabel_border;
			global::C1.Android.Chart.Resource.Attribute.c1_datalabel_borderColor = global::Sunburst101.Resource.Attribute.c1_datalabel_borderColor;
			global::C1.Android.Chart.Resource.Attribute.c1_datalabel_borderThickness = global::Sunburst101.Resource.Attribute.c1_datalabel_borderThickness;
			global::C1.Android.Chart.Resource.Attribute.c1_datalabel_connectingLine = global::Sunburst101.Resource.Attribute.c1_datalabel_connectingLine;
			global::C1.Android.Chart.Resource.Attribute.c1_datalabel_offset = global::Sunburst101.Resource.Attribute.c1_datalabel_offset;
			global::C1.Android.Chart.Resource.Attribute.c1_datalabel_position = global::Sunburst101.Resource.Attribute.c1_datalabel_position;
			global::C1.Android.Chart.Resource.Attribute.c1_datalabel_styleFill = global::Sunburst101.Resource.Attribute.c1_datalabel_styleFill;
			global::C1.Android.Chart.Resource.Attribute.c1_datalabel_styleFontSize = global::Sunburst101.Resource.Attribute.c1_datalabel_styleFontSize;
			global::C1.Android.Chart.Resource.Attribute.c1_datalabel_styleStroke = global::Sunburst101.Resource.Attribute.c1_datalabel_styleStroke;
			global::C1.Android.Chart.Resource.Attribute.c1_datalabel_styleStrokeThickness = global::Sunburst101.Resource.Attribute.c1_datalabel_styleStrokeThickness;
			global::C1.Android.Chart.Resource.Attribute.c1_datalabel_styleTypeface = global::Sunburst101.Resource.Attribute.c1_datalabel_styleTypeface;
			global::C1.Android.Chart.Resource.Attribute.c1_datalabel_styleTypefaceStyle = global::Sunburst101.Resource.Attribute.c1_datalabel_styleTypefaceStyle;
			global::C1.Android.Chart.Resource.Attribute.c1_fontFamily = global::Sunburst101.Resource.Attribute.c1_fontFamily;
			global::C1.Android.Chart.Resource.Attribute.c1_footer = global::Sunburst101.Resource.Attribute.c1_footer;
			global::C1.Android.Chart.Resource.Attribute.c1_footerFontGravity = global::Sunburst101.Resource.Attribute.c1_footerFontGravity;
			global::C1.Android.Chart.Resource.Attribute.c1_footerStyleFill = global::Sunburst101.Resource.Attribute.c1_footerStyleFill;
			global::C1.Android.Chart.Resource.Attribute.c1_footerStyleFontSize = global::Sunburst101.Resource.Attribute.c1_footerStyleFontSize;
			global::C1.Android.Chart.Resource.Attribute.c1_footerStyleStroke = global::Sunburst101.Resource.Attribute.c1_footerStyleStroke;
			global::C1.Android.Chart.Resource.Attribute.c1_footerStyleStrokeThickness = global::Sunburst101.Resource.Attribute.c1_footerStyleStrokeThickness;
			global::C1.Android.Chart.Resource.Attribute.c1_footerStyleTypeface = global::Sunburst101.Resource.Attribute.c1_footerStyleTypeface;
			global::C1.Android.Chart.Resource.Attribute.c1_footerStyleTypefaceStyle = global::Sunburst101.Resource.Attribute.c1_footerStyleTypefaceStyle;
			global::C1.Android.Chart.Resource.Attribute.c1_header = global::Sunburst101.Resource.Attribute.c1_header;
			global::C1.Android.Chart.Resource.Attribute.c1_headerFontGravity = global::Sunburst101.Resource.Attribute.c1_headerFontGravity;
			global::C1.Android.Chart.Resource.Attribute.c1_headerStyleFill = global::Sunburst101.Resource.Attribute.c1_headerStyleFill;
			global::C1.Android.Chart.Resource.Attribute.c1_headerStyleFontSize = global::Sunburst101.Resource.Attribute.c1_headerStyleFontSize;
			global::C1.Android.Chart.Resource.Attribute.c1_headerStyleStroke = global::Sunburst101.Resource.Attribute.c1_headerStyleStroke;
			global::C1.Android.Chart.Resource.Attribute.c1_headerStyleStrokeThickness = global::Sunburst101.Resource.Attribute.c1_headerStyleStrokeThickness;
			global::C1.Android.Chart.Resource.Attribute.c1_headerStyleTypeface = global::Sunburst101.Resource.Attribute.c1_headerStyleTypeface;
			global::C1.Android.Chart.Resource.Attribute.c1_headerStyleTypefaceStyle = global::Sunburst101.Resource.Attribute.c1_headerStyleTypefaceStyle;
			global::C1.Android.Chart.Resource.Attribute.c1_innerRadius = global::Sunburst101.Resource.Attribute.c1_innerRadius;
			global::C1.Android.Chart.Resource.Attribute.c1_legendOrientation = global::Sunburst101.Resource.Attribute.c1_legendOrientation;
			global::C1.Android.Chart.Resource.Attribute.c1_legendPosition = global::Sunburst101.Resource.Attribute.c1_legendPosition;
			global::C1.Android.Chart.Resource.Attribute.c1_legendStyleFill = global::Sunburst101.Resource.Attribute.c1_legendStyleFill;
			global::C1.Android.Chart.Resource.Attribute.c1_legendStyleFontSize = global::Sunburst101.Resource.Attribute.c1_legendStyleFontSize;
			global::C1.Android.Chart.Resource.Attribute.c1_legendStyleStroke = global::Sunburst101.Resource.Attribute.c1_legendStyleStroke;
			global::C1.Android.Chart.Resource.Attribute.c1_legendStyleStrokeThickness = global::Sunburst101.Resource.Attribute.c1_legendStyleStrokeThickness;
			global::C1.Android.Chart.Resource.Attribute.c1_legendStyleTypeface = global::Sunburst101.Resource.Attribute.c1_legendStyleTypeface;
			global::C1.Android.Chart.Resource.Attribute.c1_legendStyleTypefaceStyle = global::Sunburst101.Resource.Attribute.c1_legendStyleTypefaceStyle;
			global::C1.Android.Chart.Resource.Attribute.c1_legendTitle = global::Sunburst101.Resource.Attribute.c1_legendTitle;
			global::C1.Android.Chart.Resource.Attribute.c1_legendTitleStyleFill = global::Sunburst101.Resource.Attribute.c1_legendTitleStyleFill;
			global::C1.Android.Chart.Resource.Attribute.c1_legendTitleStyleFontSize = global::Sunburst101.Resource.Attribute.c1_legendTitleStyleFontSize;
			global::C1.Android.Chart.Resource.Attribute.c1_legendTitleStyleStroke = global::Sunburst101.Resource.Attribute.c1_legendTitleStyleStroke;
			global::C1.Android.Chart.Resource.Attribute.c1_legendTitleStyleStrokeThickness = global::Sunburst101.Resource.Attribute.c1_legendTitleStyleStrokeThickness;
			global::C1.Android.Chart.Resource.Attribute.c1_legendTitleStyleTypeface = global::Sunburst101.Resource.Attribute.c1_legendTitleStyleTypeface;
			global::C1.Android.Chart.Resource.Attribute.c1_legendTitleStyleTypefaceStyle = global::Sunburst101.Resource.Attribute.c1_legendTitleStyleTypefaceStyle;
			global::C1.Android.Chart.Resource.Attribute.c1_legendToggle = global::Sunburst101.Resource.Attribute.c1_legendToggle;
			global::C1.Android.Chart.Resource.Attribute.c1_offset = global::Sunburst101.Resource.Attribute.c1_offset;
			global::C1.Android.Chart.Resource.Attribute.c1_options_bubbleMaxSize = global::Sunburst101.Resource.Attribute.c1_options_bubbleMaxSize;
			global::C1.Android.Chart.Resource.Attribute.c1_options_bubbleMinSize = global::Sunburst101.Resource.Attribute.c1_options_bubbleMinSize;
			global::C1.Android.Chart.Resource.Attribute.c1_options_groupWidth = global::Sunburst101.Resource.Attribute.c1_options_groupWidth;
			global::C1.Android.Chart.Resource.Attribute.c1_palette = global::Sunburst101.Resource.Attribute.c1_palette;
			global::C1.Android.Chart.Resource.Attribute.c1_plotStyleFill = global::Sunburst101.Resource.Attribute.c1_plotStyleFill;
			global::C1.Android.Chart.Resource.Attribute.c1_plotStyleFontSize = global::Sunburst101.Resource.Attribute.c1_plotStyleFontSize;
			global::C1.Android.Chart.Resource.Attribute.c1_plotStyleStroke = global::Sunburst101.Resource.Attribute.c1_plotStyleStroke;
			global::C1.Android.Chart.Resource.Attribute.c1_plotStyleStrokeThickness = global::Sunburst101.Resource.Attribute.c1_plotStyleStrokeThickness;
			global::C1.Android.Chart.Resource.Attribute.c1_plotStyleTypeface = global::Sunburst101.Resource.Attribute.c1_plotStyleTypeface;
			global::C1.Android.Chart.Resource.Attribute.c1_plotStyleTypefaceStyle = global::Sunburst101.Resource.Attribute.c1_plotStyleTypefaceStyle;
			global::C1.Android.Chart.Resource.Attribute.c1_reversed = global::Sunburst101.Resource.Attribute.c1_reversed;
			global::C1.Android.Chart.Resource.Attribute.c1_rotated = global::Sunburst101.Resource.Attribute.c1_rotated;
			global::C1.Android.Chart.Resource.Attribute.c1_selectedIndex = global::Sunburst101.Resource.Attribute.c1_selectedIndex;
			global::C1.Android.Chart.Resource.Attribute.c1_selectedItemOffset = global::Sunburst101.Resource.Attribute.c1_selectedItemOffset;
			global::C1.Android.Chart.Resource.Attribute.c1_selectedItemPosition = global::Sunburst101.Resource.Attribute.c1_selectedItemPosition;
			global::C1.Android.Chart.Resource.Attribute.c1_selectionBackgroundColor = global::Sunburst101.Resource.Attribute.c1_selectionBackgroundColor;
			global::C1.Android.Chart.Resource.Attribute.c1_selectionMode = global::Sunburst101.Resource.Attribute.c1_selectionMode;
			global::C1.Android.Chart.Resource.Attribute.c1_selectionStyleFill = global::Sunburst101.Resource.Attribute.c1_selectionStyleFill;
			global::C1.Android.Chart.Resource.Attribute.c1_selectionStyleFontSize = global::Sunburst101.Resource.Attribute.c1_selectionStyleFontSize;
			global::C1.Android.Chart.Resource.Attribute.c1_selectionStyleStroke = global::Sunburst101.Resource.Attribute.c1_selectionStyleStroke;
			global::C1.Android.Chart.Resource.Attribute.c1_selectionStyleStrokeThickness = global::Sunburst101.Resource.Attribute.c1_selectionStyleStrokeThickness;
			global::C1.Android.Chart.Resource.Attribute.c1_selectionStyleTypeface = global::Sunburst101.Resource.Attribute.c1_selectionStyleTypeface;
			global::C1.Android.Chart.Resource.Attribute.c1_selectionStyleTypefaceStyle = global::Sunburst101.Resource.Attribute.c1_selectionStyleTypefaceStyle;
			global::C1.Android.Chart.Resource.Attribute.c1_selectionTextColor = global::Sunburst101.Resource.Attribute.c1_selectionTextColor;
			global::C1.Android.Chart.Resource.Attribute.c1_stackingType = global::Sunburst101.Resource.Attribute.c1_stackingType;
			global::C1.Android.Chart.Resource.Attribute.c1_startAngle = global::Sunburst101.Resource.Attribute.c1_startAngle;
			global::C1.Android.Chart.Resource.Attribute.c1_textColor = global::Sunburst101.Resource.Attribute.c1_textColor;
			global::C1.Android.Chart.Resource.Attribute.c1_textSize = global::Sunburst101.Resource.Attribute.c1_textSize;
			global::C1.Android.Chart.Resource.Attribute.c1_textStyle = global::Sunburst101.Resource.Attribute.c1_textStyle;
			global::C1.Android.Chart.Resource.Attribute.c1_typeface = global::Sunburst101.Resource.Attribute.c1_typeface;
			global::C1.Android.Chart.Resource.Id.ALL = global::Sunburst101.Resource.Id.ALL;
			global::C1.Android.Chart.Resource.Id.AREA = global::Sunburst101.Resource.Id.AREA;
			global::C1.Android.Chart.Resource.Id.AUTO = global::Sunburst101.Resource.Id.AUTO;
			global::C1.Android.Chart.Resource.Id.BAR = global::Sunburst101.Resource.Id.BAR;
			global::C1.Android.Chart.Resource.Id.BOLD = global::Sunburst101.Resource.Id.BOLD;
			global::C1.Android.Chart.Resource.Id.BOLD_ITALIC = global::Sunburst101.Resource.Id.BOLD_ITALIC;
			global::C1.Android.Chart.Resource.Id.BOTTOM = global::Sunburst101.Resource.Id.BOTTOM;
			global::C1.Android.Chart.Resource.Id.BUBBLE = global::Sunburst101.Resource.Id.BUBBLE;
			global::C1.Android.Chart.Resource.Id.CANDLE = global::Sunburst101.Resource.Id.CANDLE;
			global::C1.Android.Chart.Resource.Id.CENTER = global::Sunburst101.Resource.Id.CENTER;
			global::C1.Android.Chart.Resource.Id.CENTER_HORIZONTAL = global::Sunburst101.Resource.Id.CENTER_HORIZONTAL;
			global::C1.Android.Chart.Resource.Id.COLUMN = global::Sunburst101.Resource.Id.COLUMN;
			global::C1.Android.Chart.Resource.Id.Cerulean = global::Sunburst101.Resource.Id.Cerulean;
			global::C1.Android.Chart.Resource.Id.Cocoa = global::Sunburst101.Resource.Id.Cocoa;
			global::C1.Android.Chart.Resource.Id.Coral = global::Sunburst101.Resource.Id.Coral;
			global::C1.Android.Chart.Resource.Id.Cross = global::Sunburst101.Resource.Id.Cross;
			global::C1.Android.Chart.Resource.Id.Custom = global::Sunburst101.Resource.Id.Custom;
			global::C1.Android.Chart.Resource.Id.Cyborg = global::Sunburst101.Resource.Id.Cyborg;
			global::C1.Android.Chart.Resource.Id.Darkly = global::Sunburst101.Resource.Id.Darkly;
			global::C1.Android.Chart.Resource.Id.FALSE = global::Sunburst101.Resource.Id.FALSE;
			global::C1.Android.Chart.Resource.Id.Flatly = global::Sunburst101.Resource.Id.Flatly;
			global::C1.Android.Chart.Resource.Id.HLOC = global::Sunburst101.Resource.Id.HLOC;
			global::C1.Android.Chart.Resource.Id.HORIZONTAL = global::Sunburst101.Resource.Id.HORIZONTAL;
			global::C1.Android.Chart.Resource.Id.Highcontrast = global::Sunburst101.Resource.Id.Highcontrast;
			global::C1.Android.Chart.Resource.Id.INSIDE = global::Sunburst101.Resource.Id.INSIDE;
			global::C1.Android.Chart.Resource.Id.ITALIC = global::Sunburst101.Resource.Id.ITALIC;
			global::C1.Android.Chart.Resource.Id.LEFT = global::Sunburst101.Resource.Id.LEFT;
			global::C1.Android.Chart.Resource.Id.LINE = global::Sunburst101.Resource.Id.LINE;
			global::C1.Android.Chart.Resource.Id.LINESYMBOLS = global::Sunburst101.Resource.Id.LINESYMBOLS;
			global::C1.Android.Chart.Resource.Id.Light = global::Sunburst101.Resource.Id.Light;
			global::C1.Android.Chart.Resource.Id.Midnight = global::Sunburst101.Resource.Id.Midnight;
			global::C1.Android.Chart.Resource.Id.Minimal = global::Sunburst101.Resource.Id.Minimal;
			global::C1.Android.Chart.Resource.Id.Modern = global::Sunburst101.Resource.Id.Modern;
			global::C1.Android.Chart.Resource.Id.NONE = global::Sunburst101.Resource.Id.NONE;
			global::C1.Android.Chart.Resource.Id.NORMAL = global::Sunburst101.Resource.Id.NORMAL;
			global::C1.Android.Chart.Resource.Id.None = global::Sunburst101.Resource.Id.None;
			global::C1.Android.Chart.Resource.Id.OUTSIDE = global::Sunburst101.Resource.Id.OUTSIDE;
			global::C1.Android.Chart.Resource.Id.Organic = global::Sunburst101.Resource.Id.Organic;
			global::C1.Android.Chart.Resource.Id.Point = global::Sunburst101.Resource.Id.Point;
			global::C1.Android.Chart.Resource.Id.RIGHT = global::Sunburst101.Resource.Id.RIGHT;
			global::C1.Android.Chart.Resource.Id.SCATTER = global::Sunburst101.Resource.Id.SCATTER;
			global::C1.Android.Chart.Resource.Id.SHOW = global::Sunburst101.Resource.Id.SHOW;
			global::C1.Android.Chart.Resource.Id.SPLINE = global::Sunburst101.Resource.Id.SPLINE;
			global::C1.Android.Chart.Resource.Id.SPLINEAREA = global::Sunburst101.Resource.Id.SPLINEAREA;
			global::C1.Android.Chart.Resource.Id.SPLINESYMBOLS = global::Sunburst101.Resource.Id.SPLINESYMBOLS;
			global::C1.Android.Chart.Resource.Id.STACKED = global::Sunburst101.Resource.Id.STACKED;
			global::C1.Android.Chart.Resource.Id.STACKED100pc = global::Sunburst101.Resource.Id.STACKED100pc;
			global::C1.Android.Chart.Resource.Id.Series = global::Sunburst101.Resource.Id.Series;
			global::C1.Android.Chart.Resource.Id.Slate = global::Sunburst101.Resource.Id.Slate;
			global::C1.Android.Chart.Resource.Id.Standard = global::Sunburst101.Resource.Id.Standard;
			global::C1.Android.Chart.Resource.Id.Superhero = global::Sunburst101.Resource.Id.Superhero;
			global::C1.Android.Chart.Resource.Id.TOP = global::Sunburst101.Resource.Id.TOP;
			global::C1.Android.Chart.Resource.Id.TRUE = global::Sunburst101.Resource.Id.TRUE;
			global::C1.Android.Chart.Resource.Id.TURE = global::Sunburst101.Resource.Id.TURE;
			global::C1.Android.Chart.Resource.Id.VERTICAL = global::Sunburst101.Resource.Id.VERTICAL;
			global::C1.Android.Chart.Resource.Id.X = global::Sunburst101.Resource.Id.X;
			global::C1.Android.Chart.Resource.Id.Y = global::Sunburst101.Resource.Id.Y;
			global::C1.Android.Chart.Resource.Id.Zen = global::Sunburst101.Resource.Id.Zen;
			global::C1.Android.Chart.Resource.Id.bold = global::Sunburst101.Resource.Id.bold;
			global::C1.Android.Chart.Resource.Id.italic = global::Sunburst101.Resource.Id.italic;
			global::C1.Android.Chart.Resource.Id.monospace = global::Sunburst101.Resource.Id.monospace;
			global::C1.Android.Chart.Resource.Id.normal = global::Sunburst101.Resource.Id.normal;
			global::C1.Android.Chart.Resource.Id.sans = global::Sunburst101.Resource.Id.sans;
			global::C1.Android.Chart.Resource.Id.serif = global::Sunburst101.Resource.Id.serif;
			global::C1.Android.Chart.Resource.Styleable.FlexChart = global::Sunburst101.Resource.Styleable.FlexChart;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_format = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_format;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_labelAlignment = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_labelAlignment;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_labelAngle = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_labelAngle;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_labelsVisible = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_labelsVisible;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_line = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_line;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_logBase = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_logBase;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_majorGridStyleStroke = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_majorGridStyleStroke;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_majorGridStyleStrokeThickness = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_majorGridStyleStrokeThickness;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_majorGridVisible = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_majorGridVisible;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_majorTickMark = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_majorTickMark;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_majorUnit = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_majorUnit;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_max = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_max;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_min = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_min;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_minorGridStyleStroke = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_minorGridStyleStroke;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_minorGridStyleStrokeThickness = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_minorGridStyleStrokeThickness;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_minorGridVisible = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_minorGridVisible;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_minorTickMark = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_minorTickMark;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_minorUnit = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_minorUnit;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_origin = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_origin;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_overlappingLabels = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_overlappingLabels;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_position = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_position;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_reversed = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_reversed;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_styleFill = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_styleFill;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_styleFontSize = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_styleFontSize;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_styleStroke = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_styleStroke;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_styleStrokeThickness = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_styleStrokeThickness;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_styleTypeface = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_styleTypeface;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_styleTypefaceStyle = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_styleTypefaceStyle;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_title = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_title;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_titleStyleFill = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_titleStyleFill;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_titleStyleFontSize = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_titleStyleFontSize;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_titleStyleStroke = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_titleStyleStroke;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_titleStyleStrokeThickness = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_titleStyleStrokeThickness;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_titleStyleTypeface = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_titleStyleTypeface;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_titleStyleTypefaceStyle = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_titleStyleTypefaceStyle;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisX_type = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisX_type;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_format = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_format;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_labelAlignment = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_labelAlignment;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_labelAngle = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_labelAngle;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_labelsVisible = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_labelsVisible;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_line = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_line;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_logBase = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_logBase;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_majorGridStyleStroke = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_majorGridStyleStroke;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_majorGridStyleStrokeThickness = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_majorGridStyleStrokeThickness;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_majorGridVisible = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_majorGridVisible;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_majorTickMark = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_majorTickMark;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_majorUnit = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_majorUnit;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_max = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_max;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_min = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_min;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_minorGridStyleStroke = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_minorGridStyleStroke;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_minorGridStyleStrokeThickness = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_minorGridStyleStrokeThickness;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_minorGridVisible = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_minorGridVisible;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_minorTickMark = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_minorTickMark;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_minorUnit = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_minorUnit;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_origin = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_origin;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_overlappingLabels = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_overlappingLabels;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_position = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_position;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_reversed = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_reversed;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_styleFill = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_styleFill;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_styleFontSize = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_styleFontSize;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_styleStroke = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_styleStroke;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_styleStrokeThickness = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_styleStrokeThickness;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_styleTypeface = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_styleTypeface;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_styleTypefaceStyle = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_styleTypefaceStyle;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_title = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_title;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_titleStyleFill = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_titleStyleFill;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_titleStyleFontSize = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_titleStyleFontSize;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_titleStyleStroke = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_titleStyleStroke;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_titleStyleStrokeThickness = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_titleStyleStrokeThickness;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_titleStyleTypeface = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_titleStyleTypeface;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_titleStyleTypefaceStyle = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_titleStyleTypefaceStyle;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_axisY_type = global::Sunburst101.Resource.Styleable.FlexChart_c1_axisY_type;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_bindingX = global::Sunburst101.Resource.Styleable.FlexChart_c1_bindingX;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_chartType = global::Sunburst101.Resource.Styleable.FlexChart_c1_chartType;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_datalabel_border = global::Sunburst101.Resource.Styleable.FlexChart_c1_datalabel_border;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_datalabel_borderColor = global::Sunburst101.Resource.Styleable.FlexChart_c1_datalabel_borderColor;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_datalabel_borderThickness = global::Sunburst101.Resource.Styleable.FlexChart_c1_datalabel_borderThickness;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_datalabel_connectingLine = global::Sunburst101.Resource.Styleable.FlexChart_c1_datalabel_connectingLine;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_datalabel_offset = global::Sunburst101.Resource.Styleable.FlexChart_c1_datalabel_offset;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_datalabel_position = global::Sunburst101.Resource.Styleable.FlexChart_c1_datalabel_position;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_datalabel_styleFill = global::Sunburst101.Resource.Styleable.FlexChart_c1_datalabel_styleFill;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_datalabel_styleFontSize = global::Sunburst101.Resource.Styleable.FlexChart_c1_datalabel_styleFontSize;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_datalabel_styleStroke = global::Sunburst101.Resource.Styleable.FlexChart_c1_datalabel_styleStroke;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_datalabel_styleStrokeThickness = global::Sunburst101.Resource.Styleable.FlexChart_c1_datalabel_styleStrokeThickness;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_datalabel_styleTypeface = global::Sunburst101.Resource.Styleable.FlexChart_c1_datalabel_styleTypeface;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_datalabel_styleTypefaceStyle = global::Sunburst101.Resource.Styleable.FlexChart_c1_datalabel_styleTypefaceStyle;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_options_bubbleMaxSize = global::Sunburst101.Resource.Styleable.FlexChart_c1_options_bubbleMaxSize;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_options_bubbleMinSize = global::Sunburst101.Resource.Styleable.FlexChart_c1_options_bubbleMinSize;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_options_groupWidth = global::Sunburst101.Resource.Styleable.FlexChart_c1_options_groupWidth;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_rotated = global::Sunburst101.Resource.Styleable.FlexChart_c1_rotated;
			global::C1.Android.Chart.Resource.Styleable.FlexChart_c1_stackingType = global::Sunburst101.Resource.Styleable.FlexChart_c1_stackingType;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase = global::Sunburst101.Resource.Styleable.FlexChartBase;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_backgroundColor = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_backgroundColor;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_binding = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_binding;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_footer = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_footer;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_footerFontGravity = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_footerFontGravity;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_footerStyleFill = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_footerStyleFill;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_footerStyleFontSize = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_footerStyleFontSize;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_footerStyleStroke = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_footerStyleStroke;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_footerStyleStrokeThickness = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_footerStyleStrokeThickness;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_footerStyleTypeface = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_footerStyleTypeface;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_footerStyleTypefaceStyle = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_footerStyleTypefaceStyle;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_header = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_header;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_headerFontGravity = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_headerFontGravity;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_headerStyleFill = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_headerStyleFill;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_headerStyleFontSize = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_headerStyleFontSize;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_headerStyleStroke = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_headerStyleStroke;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_headerStyleStrokeThickness = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_headerStyleStrokeThickness;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_headerStyleTypeface = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_headerStyleTypeface;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_headerStyleTypefaceStyle = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_headerStyleTypefaceStyle;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_legendOrientation = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_legendOrientation;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_legendPosition = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_legendPosition;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_legendStyleFill = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_legendStyleFill;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_legendStyleFontSize = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_legendStyleFontSize;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_legendStyleStroke = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_legendStyleStroke;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_legendStyleStrokeThickness = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_legendStyleStrokeThickness;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_legendStyleTypeface = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_legendStyleTypeface;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_legendStyleTypefaceStyle = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_legendStyleTypefaceStyle;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_legendTitle = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_legendTitle;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_legendTitleStyleFill = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_legendTitleStyleFill;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_legendTitleStyleFontSize = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_legendTitleStyleFontSize;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_legendTitleStyleStroke = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_legendTitleStyleStroke;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_legendTitleStyleStrokeThickness = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_legendTitleStyleStrokeThickness;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_legendTitleStyleTypeface = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_legendTitleStyleTypeface;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_legendTitleStyleTypefaceStyle = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_legendTitleStyleTypefaceStyle;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_legendToggle = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_legendToggle;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_palette = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_palette;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_plotStyleFill = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_plotStyleFill;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_plotStyleFontSize = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_plotStyleFontSize;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_plotStyleStroke = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_plotStyleStroke;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_plotStyleStrokeThickness = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_plotStyleStrokeThickness;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_plotStyleTypeface = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_plotStyleTypeface;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_plotStyleTypefaceStyle = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_plotStyleTypefaceStyle;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_selectedIndex = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_selectedIndex;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_selectionMode = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_selectionMode;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_selectionStyleFill = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_selectionStyleFill;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_selectionStyleFontSize = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_selectionStyleFontSize;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_selectionStyleStroke = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_selectionStyleStroke;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_selectionStyleStrokeThickness = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_selectionStyleStrokeThickness;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_selectionStyleTypeface = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_selectionStyleTypeface;
			global::C1.Android.Chart.Resource.Styleable.FlexChartBase_c1_selectionStyleTypefaceStyle = global::Sunburst101.Resource.Styleable.FlexChartBase_c1_selectionStyleTypefaceStyle;
			global::C1.Android.Chart.Resource.Styleable.FlexPie = global::Sunburst101.Resource.Styleable.FlexPie;
			global::C1.Android.Chart.Resource.Styleable.FlexPie_c1_bindingName = global::Sunburst101.Resource.Styleable.FlexPie_c1_bindingName;
			global::C1.Android.Chart.Resource.Styleable.FlexPie_c1_innerRadius = global::Sunburst101.Resource.Styleable.FlexPie_c1_innerRadius;
			global::C1.Android.Chart.Resource.Styleable.FlexPie_c1_offset = global::Sunburst101.Resource.Styleable.FlexPie_c1_offset;
			global::C1.Android.Chart.Resource.Styleable.FlexPie_c1_reversed = global::Sunburst101.Resource.Styleable.FlexPie_c1_reversed;
			global::C1.Android.Chart.Resource.Styleable.FlexPie_c1_selectedItemOffset = global::Sunburst101.Resource.Styleable.FlexPie_c1_selectedItemOffset;
			global::C1.Android.Chart.Resource.Styleable.FlexPie_c1_selectedItemPosition = global::Sunburst101.Resource.Styleable.FlexPie_c1_selectedItemPosition;
			global::C1.Android.Chart.Resource.Styleable.FlexPie_c1_startAngle = global::Sunburst101.Resource.Styleable.FlexPie_c1_startAngle;
			global::C1.Android.Chart.Resource.Styleable.Sunburst = global::Sunburst101.Resource.Styleable.Sunburst;
			global::C1.Android.Chart.Resource.Styleable.Sunburst_c1_childItemsPath = global::Sunburst101.Resource.Styleable.Sunburst_c1_childItemsPath;
			global::C1.Android.Core.Resource.Attribute.c1_backgroundColor = global::Sunburst101.Resource.Attribute.c1_backgroundColor;
			global::C1.Android.Core.Resource.Attribute.c1_borderColor = global::Sunburst101.Resource.Attribute.c1_borderColor;
			global::C1.Android.Core.Resource.Attribute.c1_fontFamily = global::Sunburst101.Resource.Attribute.c1_fontFamily;
			global::C1.Android.Core.Resource.Attribute.c1_selectedIndex = global::Sunburst101.Resource.Attribute.c1_selectedIndex;
			global::C1.Android.Core.Resource.Attribute.c1_selectionBackgroundColor = global::Sunburst101.Resource.Attribute.c1_selectionBackgroundColor;
			global::C1.Android.Core.Resource.Attribute.c1_selectionTextColor = global::Sunburst101.Resource.Attribute.c1_selectionTextColor;
			global::C1.Android.Core.Resource.Attribute.c1_textColor = global::Sunburst101.Resource.Attribute.c1_textColor;
			global::C1.Android.Core.Resource.Attribute.c1_textSize = global::Sunburst101.Resource.Attribute.c1_textSize;
			global::C1.Android.Core.Resource.Attribute.c1_textStyle = global::Sunburst101.Resource.Attribute.c1_textStyle;
			global::C1.Android.Core.Resource.Attribute.c1_typeface = global::Sunburst101.Resource.Attribute.c1_typeface;
			global::C1.Android.Core.Resource.Id.bold = global::Sunburst101.Resource.Id.bold;
			global::C1.Android.Core.Resource.Id.italic = global::Sunburst101.Resource.Id.italic;
			global::C1.Android.Core.Resource.Id.monospace = global::Sunburst101.Resource.Id.monospace;
			global::C1.Android.Core.Resource.Id.normal = global::Sunburst101.Resource.Id.normal;
			global::C1.Android.Core.Resource.Id.sans = global::Sunburst101.Resource.Id.sans;
			global::C1.Android.Core.Resource.Id.serif = global::Sunburst101.Resource.Id.serif;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int legend_spinner_values = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int selection_spinner_values = 2131034113;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01004e
			public const int c1_axisX_format = 2130772046;
			
			// aapt resource value: 0x7f01004f
			public const int c1_axisX_labelAlignment = 2130772047;
			
			// aapt resource value: 0x7f010050
			public const int c1_axisX_labelAngle = 2130772048;
			
			// aapt resource value: 0x7f010054
			public const int c1_axisX_labelsVisible = 2130772052;
			
			// aapt resource value: 0x7f01004c
			public const int c1_axisX_line = 2130772044;
			
			// aapt resource value: 0x7f010051
			public const int c1_axisX_logBase = 2130772049;
			
			// aapt resource value: 0x7f010058
			public const int c1_axisX_majorGridStyleStroke = 2130772056;
			
			// aapt resource value: 0x7f010059
			public const int c1_axisX_majorGridStyleStrokeThickness = 2130772057;
			
			// aapt resource value: 0x7f010055
			public const int c1_axisX_majorGridVisible = 2130772053;
			
			// aapt resource value: 0x7f010056
			public const int c1_axisX_majorTickMark = 2130772054;
			
			// aapt resource value: 0x7f010057
			public const int c1_axisX_majorUnit = 2130772055;
			
			// aapt resource value: 0x7f010052
			public const int c1_axisX_max = 2130772050;
			
			// aapt resource value: 0x7f010053
			public const int c1_axisX_min = 2130772051;
			
			// aapt resource value: 0x7f01005d
			public const int c1_axisX_minorGridStyleStroke = 2130772061;
			
			// aapt resource value: 0x7f01005e
			public const int c1_axisX_minorGridStyleStrokeThickness = 2130772062;
			
			// aapt resource value: 0x7f01005a
			public const int c1_axisX_minorGridVisible = 2130772058;
			
			// aapt resource value: 0x7f01005b
			public const int c1_axisX_minorTickMark = 2130772059;
			
			// aapt resource value: 0x7f01005c
			public const int c1_axisX_minorUnit = 2130772060;
			
			// aapt resource value: 0x7f01005f
			public const int c1_axisX_origin = 2130772063;
			
			// aapt resource value: 0x7f010060
			public const int c1_axisX_overlappingLabels = 2130772064;
			
			// aapt resource value: 0x7f010061
			public const int c1_axisX_position = 2130772065;
			
			// aapt resource value: 0x7f010062
			public const int c1_axisX_reversed = 2130772066;
			
			// aapt resource value: 0x7f01006d
			public const int c1_axisX_styleFill = 2130772077;
			
			// aapt resource value: 0x7f01006a
			public const int c1_axisX_styleFontSize = 2130772074;
			
			// aapt resource value: 0x7f01006e
			public const int c1_axisX_styleStroke = 2130772078;
			
			// aapt resource value: 0x7f01006f
			public const int c1_axisX_styleStrokeThickness = 2130772079;
			
			// aapt resource value: 0x7f01006b
			public const int c1_axisX_styleTypeface = 2130772075;
			
			// aapt resource value: 0x7f01006c
			public const int c1_axisX_styleTypefaceStyle = 2130772076;
			
			// aapt resource value: 0x7f010063
			public const int c1_axisX_title = 2130772067;
			
			// aapt resource value: 0x7f010067
			public const int c1_axisX_titleStyleFill = 2130772071;
			
			// aapt resource value: 0x7f010064
			public const int c1_axisX_titleStyleFontSize = 2130772068;
			
			// aapt resource value: 0x7f010068
			public const int c1_axisX_titleStyleStroke = 2130772072;
			
			// aapt resource value: 0x7f010069
			public const int c1_axisX_titleStyleStrokeThickness = 2130772073;
			
			// aapt resource value: 0x7f010065
			public const int c1_axisX_titleStyleTypeface = 2130772069;
			
			// aapt resource value: 0x7f010066
			public const int c1_axisX_titleStyleTypefaceStyle = 2130772070;
			
			// aapt resource value: 0x7f01004d
			public const int c1_axisX_type = 2130772045;
			
			// aapt resource value: 0x7f010072
			public const int c1_axisY_format = 2130772082;
			
			// aapt resource value: 0x7f010073
			public const int c1_axisY_labelAlignment = 2130772083;
			
			// aapt resource value: 0x7f010074
			public const int c1_axisY_labelAngle = 2130772084;
			
			// aapt resource value: 0x7f010078
			public const int c1_axisY_labelsVisible = 2130772088;
			
			// aapt resource value: 0x7f010070
			public const int c1_axisY_line = 2130772080;
			
			// aapt resource value: 0x7f010075
			public const int c1_axisY_logBase = 2130772085;
			
			// aapt resource value: 0x7f01007c
			public const int c1_axisY_majorGridStyleStroke = 2130772092;
			
			// aapt resource value: 0x7f01007d
			public const int c1_axisY_majorGridStyleStrokeThickness = 2130772093;
			
			// aapt resource value: 0x7f010079
			public const int c1_axisY_majorGridVisible = 2130772089;
			
			// aapt resource value: 0x7f01007a
			public const int c1_axisY_majorTickMark = 2130772090;
			
			// aapt resource value: 0x7f01007b
			public const int c1_axisY_majorUnit = 2130772091;
			
			// aapt resource value: 0x7f010076
			public const int c1_axisY_max = 2130772086;
			
			// aapt resource value: 0x7f010077
			public const int c1_axisY_min = 2130772087;
			
			// aapt resource value: 0x7f010081
			public const int c1_axisY_minorGridStyleStroke = 2130772097;
			
			// aapt resource value: 0x7f010082
			public const int c1_axisY_minorGridStyleStrokeThickness = 2130772098;
			
			// aapt resource value: 0x7f01007e
			public const int c1_axisY_minorGridVisible = 2130772094;
			
			// aapt resource value: 0x7f01007f
			public const int c1_axisY_minorTickMark = 2130772095;
			
			// aapt resource value: 0x7f010080
			public const int c1_axisY_minorUnit = 2130772096;
			
			// aapt resource value: 0x7f010083
			public const int c1_axisY_origin = 2130772099;
			
			// aapt resource value: 0x7f010084
			public const int c1_axisY_overlappingLabels = 2130772100;
			
			// aapt resource value: 0x7f010085
			public const int c1_axisY_position = 2130772101;
			
			// aapt resource value: 0x7f010086
			public const int c1_axisY_reversed = 2130772102;
			
			// aapt resource value: 0x7f010091
			public const int c1_axisY_styleFill = 2130772113;
			
			// aapt resource value: 0x7f01008e
			public const int c1_axisY_styleFontSize = 2130772110;
			
			// aapt resource value: 0x7f010092
			public const int c1_axisY_styleStroke = 2130772114;
			
			// aapt resource value: 0x7f010093
			public const int c1_axisY_styleStrokeThickness = 2130772115;
			
			// aapt resource value: 0x7f01008f
			public const int c1_axisY_styleTypeface = 2130772111;
			
			// aapt resource value: 0x7f010090
			public const int c1_axisY_styleTypefaceStyle = 2130772112;
			
			// aapt resource value: 0x7f010087
			public const int c1_axisY_title = 2130772103;
			
			// aapt resource value: 0x7f01008b
			public const int c1_axisY_titleStyleFill = 2130772107;
			
			// aapt resource value: 0x7f010088
			public const int c1_axisY_titleStyleFontSize = 2130772104;
			
			// aapt resource value: 0x7f01008c
			public const int c1_axisY_titleStyleStroke = 2130772108;
			
			// aapt resource value: 0x7f01008d
			public const int c1_axisY_titleStyleStrokeThickness = 2130772109;
			
			// aapt resource value: 0x7f010089
			public const int c1_axisY_titleStyleTypeface = 2130772105;
			
			// aapt resource value: 0x7f01008a
			public const int c1_axisY_titleStyleTypefaceStyle = 2130772106;
			
			// aapt resource value: 0x7f010071
			public const int c1_axisY_type = 2130772081;
			
			// aapt resource value: 0x7f010000
			public const int c1_backgroundColor = 2130771968;
			
			// aapt resource value: 0x7f01000c
			public const int c1_binding = 2130771980;
			
			// aapt resource value: 0x7f010094
			public const int c1_bindingName = 2130772116;
			
			// aapt resource value: 0x7f01003e
			public const int c1_bindingX = 2130772030;
			
			// aapt resource value: 0x7f010006
			public const int c1_borderColor = 2130771974;
			
			// aapt resource value: 0x7f010039
			public const int c1_chartType = 2130772025;
			
			// aapt resource value: 0x7f01009b
			public const int c1_childItemsPath = 2130772123;
			
			// aapt resource value: 0x7f010040
			public const int c1_datalabel_border = 2130772032;
			
			// aapt resource value: 0x7f010042
			public const int c1_datalabel_borderColor = 2130772034;
			
			// aapt resource value: 0x7f010041
			public const int c1_datalabel_borderThickness = 2130772033;
			
			// aapt resource value: 0x7f010043
			public const int c1_datalabel_connectingLine = 2130772035;
			
			// aapt resource value: 0x7f010044
			public const int c1_datalabel_offset = 2130772036;
			
			// aapt resource value: 0x7f010045
			public const int c1_datalabel_position = 2130772037;
			
			// aapt resource value: 0x7f010049
			public const int c1_datalabel_styleFill = 2130772041;
			
			// aapt resource value: 0x7f010046
			public const int c1_datalabel_styleFontSize = 2130772038;
			
			// aapt resource value: 0x7f01004a
			public const int c1_datalabel_styleStroke = 2130772042;
			
			// aapt resource value: 0x7f01004b
			public const int c1_datalabel_styleStrokeThickness = 2130772043;
			
			// aapt resource value: 0x7f010047
			public const int c1_datalabel_styleTypeface = 2130772039;
			
			// aapt resource value: 0x7f010048
			public const int c1_datalabel_styleTypefaceStyle = 2130772040;
			
			// aapt resource value: 0x7f010004
			public const int c1_fontFamily = 2130771972;
			
			// aapt resource value: 0x7f01001c
			public const int c1_footer = 2130771996;
			
			// aapt resource value: 0x7f01001d
			public const int c1_footerFontGravity = 2130771997;
			
			// aapt resource value: 0x7f010021
			public const int c1_footerStyleFill = 2130772001;
			
			// aapt resource value: 0x7f01001e
			public const int c1_footerStyleFontSize = 2130771998;
			
			// aapt resource value: 0x7f010022
			public const int c1_footerStyleStroke = 2130772002;
			
			// aapt resource value: 0x7f010023
			public const int c1_footerStyleStrokeThickness = 2130772003;
			
			// aapt resource value: 0x7f01001f
			public const int c1_footerStyleTypeface = 2130771999;
			
			// aapt resource value: 0x7f010020
			public const int c1_footerStyleTypefaceStyle = 2130772000;
			
			// aapt resource value: 0x7f010014
			public const int c1_header = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int c1_headerFontGravity = 2130771989;
			
			// aapt resource value: 0x7f010019
			public const int c1_headerStyleFill = 2130771993;
			
			// aapt resource value: 0x7f010016
			public const int c1_headerStyleFontSize = 2130771990;
			
			// aapt resource value: 0x7f01001a
			public const int c1_headerStyleStroke = 2130771994;
			
			// aapt resource value: 0x7f01001b
			public const int c1_headerStyleStrokeThickness = 2130771995;
			
			// aapt resource value: 0x7f010017
			public const int c1_headerStyleTypeface = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int c1_headerStyleTypefaceStyle = 2130771992;
			
			// aapt resource value: 0x7f010097
			public const int c1_innerRadius = 2130772119;
			
			// aapt resource value: 0x7f010032
			public const int c1_legendOrientation = 2130772018;
			
			// aapt resource value: 0x7f010031
			public const int c1_legendPosition = 2130772017;
			
			// aapt resource value: 0x7f01002e
			public const int c1_legendStyleFill = 2130772014;
			
			// aapt resource value: 0x7f01002b
			public const int c1_legendStyleFontSize = 2130772011;
			
			// aapt resource value: 0x7f01002f
			public const int c1_legendStyleStroke = 2130772015;
			
			// aapt resource value: 0x7f010030
			public const int c1_legendStyleStrokeThickness = 2130772016;
			
			// aapt resource value: 0x7f01002c
			public const int c1_legendStyleTypeface = 2130772012;
			
			// aapt resource value: 0x7f01002d
			public const int c1_legendStyleTypefaceStyle = 2130772013;
			
			// aapt resource value: 0x7f010024
			public const int c1_legendTitle = 2130772004;
			
			// aapt resource value: 0x7f010028
			public const int c1_legendTitleStyleFill = 2130772008;
			
			// aapt resource value: 0x7f010025
			public const int c1_legendTitleStyleFontSize = 2130772005;
			
			// aapt resource value: 0x7f010029
			public const int c1_legendTitleStyleStroke = 2130772009;
			
			// aapt resource value: 0x7f01002a
			public const int c1_legendTitleStyleStrokeThickness = 2130772010;
			
			// aapt resource value: 0x7f010026
			public const int c1_legendTitleStyleTypeface = 2130772006;
			
			// aapt resource value: 0x7f010027
			public const int c1_legendTitleStyleTypefaceStyle = 2130772007;
			
			// aapt resource value: 0x7f01000d
			public const int c1_legendToggle = 2130771981;
			
			// aapt resource value: 0x7f010096
			public const int c1_offset = 2130772118;
			
			// aapt resource value: 0x7f01003c
			public const int c1_options_bubbleMaxSize = 2130772028;
			
			// aapt resource value: 0x7f01003b
			public const int c1_options_bubbleMinSize = 2130772027;
			
			// aapt resource value: 0x7f01003d
			public const int c1_options_groupWidth = 2130772029;
			
			// aapt resource value: 0x7f01000a
			public const int c1_palette = 2130771978;
			
			// aapt resource value: 0x7f010036
			public const int c1_plotStyleFill = 2130772022;
			
			// aapt resource value: 0x7f010033
			public const int c1_plotStyleFontSize = 2130772019;
			
			// aapt resource value: 0x7f010037
			public const int c1_plotStyleStroke = 2130772023;
			
			// aapt resource value: 0x7f010038
			public const int c1_plotStyleStrokeThickness = 2130772024;
			
			// aapt resource value: 0x7f010034
			public const int c1_plotStyleTypeface = 2130772020;
			
			// aapt resource value: 0x7f010035
			public const int c1_plotStyleTypefaceStyle = 2130772021;
			
			// aapt resource value: 0x7f010095
			public const int c1_reversed = 2130772117;
			
			// aapt resource value: 0x7f01003f
			public const int c1_rotated = 2130772031;
			
			// aapt resource value: 0x7f010009
			public const int c1_selectedIndex = 2130771977;
			
			// aapt resource value: 0x7f010099
			public const int c1_selectedItemOffset = 2130772121;
			
			// aapt resource value: 0x7f01009a
			public const int c1_selectedItemPosition = 2130772122;
			
			// aapt resource value: 0x7f010007
			public const int c1_selectionBackgroundColor = 2130771975;
			
			// aapt resource value: 0x7f01000b
			public const int c1_selectionMode = 2130771979;
			
			// aapt resource value: 0x7f010011
			public const int c1_selectionStyleFill = 2130771985;
			
			// aapt resource value: 0x7f01000e
			public const int c1_selectionStyleFontSize = 2130771982;
			
			// aapt resource value: 0x7f010012
			public const int c1_selectionStyleStroke = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int c1_selectionStyleStrokeThickness = 2130771987;
			
			// aapt resource value: 0x7f01000f
			public const int c1_selectionStyleTypeface = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int c1_selectionStyleTypefaceStyle = 2130771984;
			
			// aapt resource value: 0x7f010008
			public const int c1_selectionTextColor = 2130771976;
			
			// aapt resource value: 0x7f01003a
			public const int c1_stackingType = 2130772026;
			
			// aapt resource value: 0x7f010098
			public const int c1_startAngle = 2130772120;
			
			// aapt resource value: 0x7f010001
			public const int c1_textColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int c1_textSize = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int c1_textStyle = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int c1_typeface = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow_down_red = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow_up_green = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int BasicFeatures = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int downArrow = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int GettingStarted = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int GroupCollection = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int LegendAndTitles = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Selection = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int upArrow = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070025
			public const int ALL = 2131165221;
			
			// aapt resource value: 0x7f070028
			public const int AREA = 2131165224;
			
			// aapt resource value: 0x7f070021
			public const int AUTO = 2131165217;
			
			// aapt resource value: 0x7f070029
			public const int BAR = 2131165225;
			
			// aapt resource value: 0x7f07001a
			public const int BOLD = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int BOLD_ITALIC = 2131165211;
			
			// aapt resource value: 0x7f070022
			public const int BOTTOM = 2131165218;
			
			// aapt resource value: 0x7f07002a
			public const int BUBBLE = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int CANDLE = 2131165227;
			
			// aapt resource value: 0x7f070038
			public const int CENTER = 2131165240;
			
			// aapt resource value: 0x7f07001e
			public const int CENTER_HORIZONTAL = 2131165214;
			
			// aapt resource value: 0x7f07002c
			public const int COLUMN = 2131165228;
			
			// aapt resource value: 0x7f070006
			public const int Cerulean = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int Cocoa = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int Coral = 2131165192;
			
			// aapt resource value: 0x7f07003b
			public const int Cross = 2131165243;
			
			// aapt resource value: 0x7f070009
			public const int Custom = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int Cyborg = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int Darkly = 2131165195;
			
			// aapt resource value: 0x7f070036
			public const int FALSE = 2131165238;
			
			// aapt resource value: 0x7f07000c
			public const int Flatly = 2131165196;
			
			// aapt resource value: 0x7f07002d
			public const int HLOC = 2131165229;
			
			// aapt resource value: 0x7f070026
			public const int HORIZONTAL = 2131165222;
			
			// aapt resource value: 0x7f07000d
			public const int Highcontrast = 2131165197;
			
			// aapt resource value: 0x7f07003c
			public const int INSIDE = 2131165244;
			
			// aapt resource value: 0x7f07001c
			public const int ITALIC = 2131165212;
			
			// aapt resource value: 0x7f07001f
			public const int LEFT = 2131165215;
			
			// aapt resource value: 0x7f07002e
			public const int LINE = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int LINESYMBOLS = 2131165231;
			
			// aapt resource value: 0x7f07000e
			public const int Light = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int Midnight = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int Minimal = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int Modern = 2131165201;
			
			// aapt resource value: 0x7f070023
			public const int NONE = 2131165219;
			
			// aapt resource value: 0x7f07001d
			public const int NORMAL = 2131165213;
			
			// aapt resource value: 0x7f070017
			public const int None = 2131165207;
			
			// aapt resource value: 0x7f07003d
			public const int OUTSIDE = 2131165245;
			
			// aapt resource value: 0x7f070012
			public const int Organic = 2131165202;
			
			// aapt resource value: 0x7f070018
			public const int Point = 2131165208;
			
			// aapt resource value: 0x7f070020
			public const int RIGHT = 2131165216;
			
			// aapt resource value: 0x7f070030
			public const int SCATTER = 2131165232;
			
			// aapt resource value: 0x7f07003e
			public const int SHOW = 2131165246;
			
			// aapt resource value: 0x7f070031
			public const int SPLINE = 2131165233;
			
			// aapt resource value: 0x7f070032
			public const int SPLINEAREA = 2131165234;
			
			// aapt resource value: 0x7f070033
			public const int SPLINESYMBOLS = 2131165235;
			
			// aapt resource value: 0x7f070034
			public const int STACKED = 2131165236;
			
			// aapt resource value: 0x7f070035
			public const int STACKED100pc = 2131165237;
			
			// aapt resource value: 0x7f070019
			public const int Series = 2131165209;
			
			// aapt resource value: 0x7f070013
			public const int Slate = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int Standard = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int Superhero = 2131165205;
			
			// aapt resource value: 0x7f070024
			public const int TOP = 2131165220;
			
			// aapt resource value: 0x7f070037
			public const int TRUE = 2131165239;
			
			// aapt resource value: 0x7f07003f
			public const int TURE = 2131165247;
			
			// aapt resource value: 0x7f070027
			public const int VERTICAL = 2131165223;
			
			// aapt resource value: 0x7f070039
			public const int X = 2131165241;
			
			// aapt resource value: 0x7f07003a
			public const int Y = 2131165242;
			
			// aapt resource value: 0x7f070016
			public const int Zen = 2131165206;
			
			// aapt resource value: 0x7f070000
			public const int bold = 2131165184;
			
			// aapt resource value: 0x7f070042
			public const int buttonMinus = 2131165250;
			
			// aapt resource value: 0x7f070043
			public const int buttonPlus = 2131165251;
			
			// aapt resource value: 0x7f07004b
			public const int donutPie = 2131165259;
			
			// aapt resource value: 0x7f07004a
			public const int flexPie = 2131165258;
			
			// aapt resource value: 0x7f07004d
			public const int footer = 2131165261;
			
			// aapt resource value: 0x7f07004f
			public const int footerValue = 2131165263;
			
			// aapt resource value: 0x7f07004c
			public const int header = 2131165260;
			
			// aapt resource value: 0x7f07004e
			public const int headerValue = 2131165262;
			
			// aapt resource value: 0x7f070040
			public const int innerRadius = 2131165248;
			
			// aapt resource value: 0x7f070001
			public const int italic = 2131165185;
			
			// aapt resource value: 0x7f070052
			public const int itemOffset = 2131165266;
			
			// aapt resource value: 0x7f070050
			public const int legendPosition = 2131165264;
			
			// aapt resource value: 0x7f070051
			public const int legendSpinner = 2131165265;
			
			// aapt resource value: 0x7f070003
			public const int monospace = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int normal = 2131165186;
			
			// aapt resource value: 0x7f070044
			public const int offset = 2131165252;
			
			// aapt resource value: 0x7f070045
			public const int offsetSeekBar = 2131165253;
			
			// aapt resource value: 0x7f070053
			public const int position = 2131165267;
			
			// aapt resource value: 0x7f070041
			public const int radius = 2131165249;
			
			// aapt resource value: 0x7f070048
			public const int reversedSwitch = 2131165256;
			
			// aapt resource value: 0x7f070058
			public const int sampleDesc = 2131165272;
			
			// aapt resource value: 0x7f070056
			public const int sampleImage = 2131165270;
			
			// aapt resource value: 0x7f070057
			public const int sampleName = 2131165271;
			
			// aapt resource value: 0x7f070055
			public const int sample_list = 2131165269;
			
			// aapt resource value: 0x7f070004
			public const int sans = 2131165188;
			
			// aapt resource value: 0x7f070054
			public const int selectionSpinner = 2131165268;
			
			// aapt resource value: 0x7f070005
			public const int serif = 2131165189;
			
			// aapt resource value: 0x7f070046
			public const int startAngle = 2131165254;
			
			// aapt resource value: 0x7f070047
			public const int startAngleSeekBar = 2131165255;
			
			// aapt resource value: 0x7f070049
			public const int sunburst = 2131165257;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_basic_features = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_getting_started = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_legend_and_titles = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_selection = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int custom_list = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int appName = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int basic_features = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int basic_features_desc = 2130968582;
			
			// aapt resource value: 0x7f040012
			public const int footer = 2130968594;
			
			// aapt resource value: 0x7f040014
			public const int footer_value = 2130968596;
			
			// aapt resource value: 0x7f040001
			public const int getting_started = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int getting_started_desc = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int group_collection = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int group_collection_desc = 2130968580;
			
			// aapt resource value: 0x7f040011
			public const int header = 2130968593;
			
			// aapt resource value: 0x7f040013
			public const int header_value = 2130968595;
			
			// aapt resource value: 0x7f04000b
			public const int inner_radius = 2130968587;
			
			// aapt resource value: 0x7f040016
			public const int item_offset = 2130968598;
			
			// aapt resource value: 0x7f040007
			public const int legend_and_titles = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int legend_and_titles_desc = 2130968584;
			
			// aapt resource value: 0x7f040015
			public const int legend_position = 2130968597;
			
			// aapt resource value: 0x7f04000f
			public const int minus = 2130968591;
			
			// aapt resource value: 0x7f04000c
			public const int offset = 2130968588;
			
			// aapt resource value: 0x7f040010
			public const int plus = 2130968592;
			
			// aapt resource value: 0x7f040017
			public const int position = 2130968599;
			
			// aapt resource value: 0x7f04000e
			public const int reversed = 2130968590;
			
			// aapt resource value: 0x7f040009
			public const int selection = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int selection_desc = 2130968586;
			
			// aapt resource value: 0x7f04000d
			public const int start_angle = 2130968589;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int AppTheme = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FlexChart = new int[] {
					2130772025,
					2130772026,
					2130772027,
					2130772028,
					2130772029,
					2130772030,
					2130772031,
					2130772032,
					2130772033,
					2130772034,
					2130772035,
					2130772036,
					2130772037,
					2130772038,
					2130772039,
					2130772040,
					2130772041,
					2130772042,
					2130772043,
					2130772044,
					2130772045,
					2130772046,
					2130772047,
					2130772048,
					2130772049,
					2130772050,
					2130772051,
					2130772052,
					2130772053,
					2130772054,
					2130772055,
					2130772056,
					2130772057,
					2130772058,
					2130772059,
					2130772060,
					2130772061,
					2130772062,
					2130772063,
					2130772064,
					2130772065,
					2130772066,
					2130772067,
					2130772068,
					2130772069,
					2130772070,
					2130772071,
					2130772072,
					2130772073,
					2130772074,
					2130772075,
					2130772076,
					2130772077,
					2130772078,
					2130772079,
					2130772080,
					2130772081,
					2130772082,
					2130772083,
					2130772084,
					2130772085,
					2130772086,
					2130772087,
					2130772088,
					2130772089,
					2130772090,
					2130772091,
					2130772092,
					2130772093,
					2130772094,
					2130772095,
					2130772096,
					2130772097,
					2130772098,
					2130772099,
					2130772100,
					2130772101,
					2130772102,
					2130772103,
					2130772104,
					2130772105,
					2130772106,
					2130772107,
					2130772108,
					2130772109,
					2130772110,
					2130772111,
					2130772112,
					2130772113,
					2130772114,
					2130772115};
			
			// aapt resource value: 21
			public const int FlexChart_c1_axisX_format = 21;
			
			// aapt resource value: 22
			public const int FlexChart_c1_axisX_labelAlignment = 22;
			
			// aapt resource value: 23
			public const int FlexChart_c1_axisX_labelAngle = 23;
			
			// aapt resource value: 27
			public const int FlexChart_c1_axisX_labelsVisible = 27;
			
			// aapt resource value: 19
			public const int FlexChart_c1_axisX_line = 19;
			
			// aapt resource value: 24
			public const int FlexChart_c1_axisX_logBase = 24;
			
			// aapt resource value: 31
			public const int FlexChart_c1_axisX_majorGridStyleStroke = 31;
			
			// aapt resource value: 32
			public const int FlexChart_c1_axisX_majorGridStyleStrokeThickness = 32;
			
			// aapt resource value: 28
			public const int FlexChart_c1_axisX_majorGridVisible = 28;
			
			// aapt resource value: 29
			public const int FlexChart_c1_axisX_majorTickMark = 29;
			
			// aapt resource value: 30
			public const int FlexChart_c1_axisX_majorUnit = 30;
			
			// aapt resource value: 25
			public const int FlexChart_c1_axisX_max = 25;
			
			// aapt resource value: 26
			public const int FlexChart_c1_axisX_min = 26;
			
			// aapt resource value: 36
			public const int FlexChart_c1_axisX_minorGridStyleStroke = 36;
			
			// aapt resource value: 37
			public const int FlexChart_c1_axisX_minorGridStyleStrokeThickness = 37;
			
			// aapt resource value: 33
			public const int FlexChart_c1_axisX_minorGridVisible = 33;
			
			// aapt resource value: 34
			public const int FlexChart_c1_axisX_minorTickMark = 34;
			
			// aapt resource value: 35
			public const int FlexChart_c1_axisX_minorUnit = 35;
			
			// aapt resource value: 38
			public const int FlexChart_c1_axisX_origin = 38;
			
			// aapt resource value: 39
			public const int FlexChart_c1_axisX_overlappingLabels = 39;
			
			// aapt resource value: 40
			public const int FlexChart_c1_axisX_position = 40;
			
			// aapt resource value: 41
			public const int FlexChart_c1_axisX_reversed = 41;
			
			// aapt resource value: 52
			public const int FlexChart_c1_axisX_styleFill = 52;
			
			// aapt resource value: 49
			public const int FlexChart_c1_axisX_styleFontSize = 49;
			
			// aapt resource value: 53
			public const int FlexChart_c1_axisX_styleStroke = 53;
			
			// aapt resource value: 54
			public const int FlexChart_c1_axisX_styleStrokeThickness = 54;
			
			// aapt resource value: 50
			public const int FlexChart_c1_axisX_styleTypeface = 50;
			
			// aapt resource value: 51
			public const int FlexChart_c1_axisX_styleTypefaceStyle = 51;
			
			// aapt resource value: 42
			public const int FlexChart_c1_axisX_title = 42;
			
			// aapt resource value: 46
			public const int FlexChart_c1_axisX_titleStyleFill = 46;
			
			// aapt resource value: 43
			public const int FlexChart_c1_axisX_titleStyleFontSize = 43;
			
			// aapt resource value: 47
			public const int FlexChart_c1_axisX_titleStyleStroke = 47;
			
			// aapt resource value: 48
			public const int FlexChart_c1_axisX_titleStyleStrokeThickness = 48;
			
			// aapt resource value: 44
			public const int FlexChart_c1_axisX_titleStyleTypeface = 44;
			
			// aapt resource value: 45
			public const int FlexChart_c1_axisX_titleStyleTypefaceStyle = 45;
			
			// aapt resource value: 20
			public const int FlexChart_c1_axisX_type = 20;
			
			// aapt resource value: 57
			public const int FlexChart_c1_axisY_format = 57;
			
			// aapt resource value: 58
			public const int FlexChart_c1_axisY_labelAlignment = 58;
			
			// aapt resource value: 59
			public const int FlexChart_c1_axisY_labelAngle = 59;
			
			// aapt resource value: 63
			public const int FlexChart_c1_axisY_labelsVisible = 63;
			
			// aapt resource value: 55
			public const int FlexChart_c1_axisY_line = 55;
			
			// aapt resource value: 60
			public const int FlexChart_c1_axisY_logBase = 60;
			
			// aapt resource value: 67
			public const int FlexChart_c1_axisY_majorGridStyleStroke = 67;
			
			// aapt resource value: 68
			public const int FlexChart_c1_axisY_majorGridStyleStrokeThickness = 68;
			
			// aapt resource value: 64
			public const int FlexChart_c1_axisY_majorGridVisible = 64;
			
			// aapt resource value: 65
			public const int FlexChart_c1_axisY_majorTickMark = 65;
			
			// aapt resource value: 66
			public const int FlexChart_c1_axisY_majorUnit = 66;
			
			// aapt resource value: 61
			public const int FlexChart_c1_axisY_max = 61;
			
			// aapt resource value: 62
			public const int FlexChart_c1_axisY_min = 62;
			
			// aapt resource value: 72
			public const int FlexChart_c1_axisY_minorGridStyleStroke = 72;
			
			// aapt resource value: 73
			public const int FlexChart_c1_axisY_minorGridStyleStrokeThickness = 73;
			
			// aapt resource value: 69
			public const int FlexChart_c1_axisY_minorGridVisible = 69;
			
			// aapt resource value: 70
			public const int FlexChart_c1_axisY_minorTickMark = 70;
			
			// aapt resource value: 71
			public const int FlexChart_c1_axisY_minorUnit = 71;
			
			// aapt resource value: 74
			public const int FlexChart_c1_axisY_origin = 74;
			
			// aapt resource value: 75
			public const int FlexChart_c1_axisY_overlappingLabels = 75;
			
			// aapt resource value: 76
			public const int FlexChart_c1_axisY_position = 76;
			
			// aapt resource value: 77
			public const int FlexChart_c1_axisY_reversed = 77;
			
			// aapt resource value: 88
			public const int FlexChart_c1_axisY_styleFill = 88;
			
			// aapt resource value: 85
			public const int FlexChart_c1_axisY_styleFontSize = 85;
			
			// aapt resource value: 89
			public const int FlexChart_c1_axisY_styleStroke = 89;
			
			// aapt resource value: 90
			public const int FlexChart_c1_axisY_styleStrokeThickness = 90;
			
			// aapt resource value: 86
			public const int FlexChart_c1_axisY_styleTypeface = 86;
			
			// aapt resource value: 87
			public const int FlexChart_c1_axisY_styleTypefaceStyle = 87;
			
			// aapt resource value: 78
			public const int FlexChart_c1_axisY_title = 78;
			
			// aapt resource value: 82
			public const int FlexChart_c1_axisY_titleStyleFill = 82;
			
			// aapt resource value: 79
			public const int FlexChart_c1_axisY_titleStyleFontSize = 79;
			
			// aapt resource value: 83
			public const int FlexChart_c1_axisY_titleStyleStroke = 83;
			
			// aapt resource value: 84
			public const int FlexChart_c1_axisY_titleStyleStrokeThickness = 84;
			
			// aapt resource value: 80
			public const int FlexChart_c1_axisY_titleStyleTypeface = 80;
			
			// aapt resource value: 81
			public const int FlexChart_c1_axisY_titleStyleTypefaceStyle = 81;
			
			// aapt resource value: 56
			public const int FlexChart_c1_axisY_type = 56;
			
			// aapt resource value: 5
			public const int FlexChart_c1_bindingX = 5;
			
			// aapt resource value: 0
			public const int FlexChart_c1_chartType = 0;
			
			// aapt resource value: 7
			public const int FlexChart_c1_datalabel_border = 7;
			
			// aapt resource value: 9
			public const int FlexChart_c1_datalabel_borderColor = 9;
			
			// aapt resource value: 8
			public const int FlexChart_c1_datalabel_borderThickness = 8;
			
			// aapt resource value: 10
			public const int FlexChart_c1_datalabel_connectingLine = 10;
			
			// aapt resource value: 11
			public const int FlexChart_c1_datalabel_offset = 11;
			
			// aapt resource value: 12
			public const int FlexChart_c1_datalabel_position = 12;
			
			// aapt resource value: 16
			public const int FlexChart_c1_datalabel_styleFill = 16;
			
			// aapt resource value: 13
			public const int FlexChart_c1_datalabel_styleFontSize = 13;
			
			// aapt resource value: 17
			public const int FlexChart_c1_datalabel_styleStroke = 17;
			
			// aapt resource value: 18
			public const int FlexChart_c1_datalabel_styleStrokeThickness = 18;
			
			// aapt resource value: 14
			public const int FlexChart_c1_datalabel_styleTypeface = 14;
			
			// aapt resource value: 15
			public const int FlexChart_c1_datalabel_styleTypefaceStyle = 15;
			
			// aapt resource value: 3
			public const int FlexChart_c1_options_bubbleMaxSize = 3;
			
			// aapt resource value: 2
			public const int FlexChart_c1_options_bubbleMinSize = 2;
			
			// aapt resource value: 4
			public const int FlexChart_c1_options_groupWidth = 4;
			
			// aapt resource value: 6
			public const int FlexChart_c1_rotated = 6;
			
			// aapt resource value: 1
			public const int FlexChart_c1_stackingType = 1;
			
			public static int[] FlexChartBase = new int[] {
					2130771968,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021,
					2130772022,
					2130772023,
					2130772024};
			
			// aapt resource value: 0
			public const int FlexChartBase_c1_backgroundColor = 0;
			
			// aapt resource value: 4
			public const int FlexChartBase_c1_binding = 4;
			
			// aapt resource value: 20
			public const int FlexChartBase_c1_footer = 20;
			
			// aapt resource value: 21
			public const int FlexChartBase_c1_footerFontGravity = 21;
			
			// aapt resource value: 25
			public const int FlexChartBase_c1_footerStyleFill = 25;
			
			// aapt resource value: 22
			public const int FlexChartBase_c1_footerStyleFontSize = 22;
			
			// aapt resource value: 26
			public const int FlexChartBase_c1_footerStyleStroke = 26;
			
			// aapt resource value: 27
			public const int FlexChartBase_c1_footerStyleStrokeThickness = 27;
			
			// aapt resource value: 23
			public const int FlexChartBase_c1_footerStyleTypeface = 23;
			
			// aapt resource value: 24
			public const int FlexChartBase_c1_footerStyleTypefaceStyle = 24;
			
			// aapt resource value: 12
			public const int FlexChartBase_c1_header = 12;
			
			// aapt resource value: 13
			public const int FlexChartBase_c1_headerFontGravity = 13;
			
			// aapt resource value: 17
			public const int FlexChartBase_c1_headerStyleFill = 17;
			
			// aapt resource value: 14
			public const int FlexChartBase_c1_headerStyleFontSize = 14;
			
			// aapt resource value: 18
			public const int FlexChartBase_c1_headerStyleStroke = 18;
			
			// aapt resource value: 19
			public const int FlexChartBase_c1_headerStyleStrokeThickness = 19;
			
			// aapt resource value: 15
			public const int FlexChartBase_c1_headerStyleTypeface = 15;
			
			// aapt resource value: 16
			public const int FlexChartBase_c1_headerStyleTypefaceStyle = 16;
			
			// aapt resource value: 42
			public const int FlexChartBase_c1_legendOrientation = 42;
			
			// aapt resource value: 41
			public const int FlexChartBase_c1_legendPosition = 41;
			
			// aapt resource value: 38
			public const int FlexChartBase_c1_legendStyleFill = 38;
			
			// aapt resource value: 35
			public const int FlexChartBase_c1_legendStyleFontSize = 35;
			
			// aapt resource value: 39
			public const int FlexChartBase_c1_legendStyleStroke = 39;
			
			// aapt resource value: 40
			public const int FlexChartBase_c1_legendStyleStrokeThickness = 40;
			
			// aapt resource value: 36
			public const int FlexChartBase_c1_legendStyleTypeface = 36;
			
			// aapt resource value: 37
			public const int FlexChartBase_c1_legendStyleTypefaceStyle = 37;
			
			// aapt resource value: 28
			public const int FlexChartBase_c1_legendTitle = 28;
			
			// aapt resource value: 32
			public const int FlexChartBase_c1_legendTitleStyleFill = 32;
			
			// aapt resource value: 29
			public const int FlexChartBase_c1_legendTitleStyleFontSize = 29;
			
			// aapt resource value: 33
			public const int FlexChartBase_c1_legendTitleStyleStroke = 33;
			
			// aapt resource value: 34
			public const int FlexChartBase_c1_legendTitleStyleStrokeThickness = 34;
			
			// aapt resource value: 30
			public const int FlexChartBase_c1_legendTitleStyleTypeface = 30;
			
			// aapt resource value: 31
			public const int FlexChartBase_c1_legendTitleStyleTypefaceStyle = 31;
			
			// aapt resource value: 5
			public const int FlexChartBase_c1_legendToggle = 5;
			
			// aapt resource value: 2
			public const int FlexChartBase_c1_palette = 2;
			
			// aapt resource value: 46
			public const int FlexChartBase_c1_plotStyleFill = 46;
			
			// aapt resource value: 43
			public const int FlexChartBase_c1_plotStyleFontSize = 43;
			
			// aapt resource value: 47
			public const int FlexChartBase_c1_plotStyleStroke = 47;
			
			// aapt resource value: 48
			public const int FlexChartBase_c1_plotStyleStrokeThickness = 48;
			
			// aapt resource value: 44
			public const int FlexChartBase_c1_plotStyleTypeface = 44;
			
			// aapt resource value: 45
			public const int FlexChartBase_c1_plotStyleTypefaceStyle = 45;
			
			// aapt resource value: 1
			public const int FlexChartBase_c1_selectedIndex = 1;
			
			// aapt resource value: 3
			public const int FlexChartBase_c1_selectionMode = 3;
			
			// aapt resource value: 9
			public const int FlexChartBase_c1_selectionStyleFill = 9;
			
			// aapt resource value: 6
			public const int FlexChartBase_c1_selectionStyleFontSize = 6;
			
			// aapt resource value: 10
			public const int FlexChartBase_c1_selectionStyleStroke = 10;
			
			// aapt resource value: 11
			public const int FlexChartBase_c1_selectionStyleStrokeThickness = 11;
			
			// aapt resource value: 7
			public const int FlexChartBase_c1_selectionStyleTypeface = 7;
			
			// aapt resource value: 8
			public const int FlexChartBase_c1_selectionStyleTypefaceStyle = 8;
			
			public static int[] FlexPie = new int[] {
					2130772116,
					2130772117,
					2130772118,
					2130772119,
					2130772120,
					2130772121,
					2130772122};
			
			// aapt resource value: 0
			public const int FlexPie_c1_bindingName = 0;
			
			// aapt resource value: 3
			public const int FlexPie_c1_innerRadius = 3;
			
			// aapt resource value: 2
			public const int FlexPie_c1_offset = 2;
			
			// aapt resource value: 1
			public const int FlexPie_c1_reversed = 1;
			
			// aapt resource value: 5
			public const int FlexPie_c1_selectedItemOffset = 5;
			
			// aapt resource value: 6
			public const int FlexPie_c1_selectedItemPosition = 6;
			
			// aapt resource value: 4
			public const int FlexPie_c1_startAngle = 4;
			
			public static int[] Sunburst = new int[] {
					2130772123};
			
			// aapt resource value: 0
			public const int Sunburst_c1_childItemsPath = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
