#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("C1Gauge101.Android.Resource", IsApplication=true)]

namespace C1Gauge101.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::C1.Android.Core.Resource.Attribute.c1_backgroundColor = global::C1Gauge101.Android.Resource.Attribute.c1_backgroundColor;
			global::C1.Android.Core.Resource.Attribute.c1_borderColor = global::C1Gauge101.Android.Resource.Attribute.c1_borderColor;
			global::C1.Android.Core.Resource.Attribute.c1_fontFamily = global::C1Gauge101.Android.Resource.Attribute.c1_fontFamily;
			global::C1.Android.Core.Resource.Attribute.c1_selectedIndex = global::C1Gauge101.Android.Resource.Attribute.c1_selectedIndex;
			global::C1.Android.Core.Resource.Attribute.c1_selectionBackgroundColor = global::C1Gauge101.Android.Resource.Attribute.c1_selectionBackgroundColor;
			global::C1.Android.Core.Resource.Attribute.c1_selectionTextColor = global::C1Gauge101.Android.Resource.Attribute.c1_selectionTextColor;
			global::C1.Android.Core.Resource.Attribute.c1_textColor = global::C1Gauge101.Android.Resource.Attribute.c1_textColor;
			global::C1.Android.Core.Resource.Attribute.c1_textSize = global::C1Gauge101.Android.Resource.Attribute.c1_textSize;
			global::C1.Android.Core.Resource.Attribute.c1_textStyle = global::C1Gauge101.Android.Resource.Attribute.c1_textStyle;
			global::C1.Android.Core.Resource.Attribute.c1_typeface = global::C1Gauge101.Android.Resource.Attribute.c1_typeface;
			global::C1.Android.Core.Resource.Id.bold = global::C1Gauge101.Android.Resource.Id.bold;
			global::C1.Android.Core.Resource.Id.italic = global::C1Gauge101.Android.Resource.Id.italic;
			global::C1.Android.Core.Resource.Id.monospace = global::C1Gauge101.Android.Resource.Id.monospace;
			global::C1.Android.Core.Resource.Id.normal = global::C1Gauge101.Android.Resource.Id.normal;
			global::C1.Android.Core.Resource.Id.sans = global::C1Gauge101.Android.Resource.Id.sans;
			global::C1.Android.Core.Resource.Id.serif = global::C1Gauge101.Android.Resource.Id.serif;
			global::C1.Android.Gauge.Resource.Attribute.c1_backgroundColor = global::C1Gauge101.Android.Resource.Attribute.c1_backgroundColor;
			global::C1.Android.Gauge.Resource.Attribute.c1_borderColor = global::C1Gauge101.Android.Resource.Attribute.c1_borderColor;
			global::C1.Android.Gauge.Resource.Attribute.c1_fontFamily = global::C1Gauge101.Android.Resource.Attribute.c1_fontFamily;
			global::C1.Android.Gauge.Resource.Attribute.c1_selectedIndex = global::C1Gauge101.Android.Resource.Attribute.c1_selectedIndex;
			global::C1.Android.Gauge.Resource.Attribute.c1_selectionBackgroundColor = global::C1Gauge101.Android.Resource.Attribute.c1_selectionBackgroundColor;
			global::C1.Android.Gauge.Resource.Attribute.c1_selectionTextColor = global::C1Gauge101.Android.Resource.Attribute.c1_selectionTextColor;
			global::C1.Android.Gauge.Resource.Attribute.c1_textColor = global::C1Gauge101.Android.Resource.Attribute.c1_textColor;
			global::C1.Android.Gauge.Resource.Attribute.c1_textSize = global::C1Gauge101.Android.Resource.Attribute.c1_textSize;
			global::C1.Android.Gauge.Resource.Attribute.c1_textStyle = global::C1Gauge101.Android.Resource.Attribute.c1_textStyle;
			global::C1.Android.Gauge.Resource.Attribute.c1_typeface = global::C1Gauge101.Android.Resource.Attribute.c1_typeface;
			global::C1.Android.Gauge.Resource.Id.bold = global::C1Gauge101.Android.Resource.Id.bold;
			global::C1.Android.Gauge.Resource.Id.italic = global::C1Gauge101.Android.Resource.Id.italic;
			global::C1.Android.Gauge.Resource.Id.monospace = global::C1Gauge101.Android.Resource.Id.monospace;
			global::C1.Android.Gauge.Resource.Id.normal = global::C1Gauge101.Android.Resource.Id.normal;
			global::C1.Android.Gauge.Resource.Id.sans = global::C1Gauge101.Android.Resource.Id.sans;
			global::C1.Android.Gauge.Resource.Id.serif = global::C1Gauge101.Android.Resource.Id.serif;
			global::C1.Android.Gauge.Resource.Styleable.C1Gauge = global::C1Gauge101.Android.Resource.Styleable.C1Gauge;
			global::C1.Android.Gauge.Resource.Styleable.C1Gauge_c1_backgroundColor = global::C1Gauge101.Android.Resource.Styleable.C1Gauge_c1_backgroundColor;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int c1_backgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010006
			public const int c1_borderColor = 2130771974;
			
			// aapt resource value: 0x7f010004
			public const int c1_fontFamily = 2130771972;
			
			// aapt resource value: 0x7f010009
			public const int c1_selectedIndex = 2130771977;
			
			// aapt resource value: 0x7f010007
			public const int c1_selectionBackgroundColor = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int c1_selectionTextColor = 2130771976;
			
			// aapt resource value: 0x7f010001
			public const int c1_textColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int c1_textSize = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int c1_textStyle = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int c1_typeface = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_camera = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_save = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int MyButton = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int bold = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int italic = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int monospace = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int normal = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int sans = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int serif = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] C1Gauge = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int C1Gauge_c1_backgroundColor = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
