//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexChart101.Resources {
    using System;
    using System.Reflection;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlexChart101.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddPoint {
            get {
                return ResourceManager.GetString("AddPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation Mode.
        /// </summary>
        public static string AnimationMode {
            get {
                return ResourceManager.GetString("AnimationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to display annotations on FlexChart..
        /// </summary>
        public static string AnnotationDescription {
            get {
                return ResourceManager.GetString("AnnotationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation Localization.
        /// </summary>
        public static string AnnotationLocalization {
            get {
                return ResourceManager.GetString("AnnotationLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotations.
        /// </summary>
        public static string AnnotationTitle {
            get {
                return ResourceManager.GetString("AnnotationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the basic chart types and stacking options..
        /// </summary>
        public static string BasicChartTypesDescription {
            get {
                return ResourceManager.GetString("BasicChartTypesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Chart Types.
        /// </summary>
        public static string BasicChartTypesTitle {
            get {
                return ResourceManager.GetString("BasicChartTypesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BinWidth.
        /// </summary>
        public static string BinWidth {
            get {
                return ResourceManager.GetString("BinWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a bubble chart..
        /// </summary>
        public static string BubbleChartDescription {
            get {
                return ResourceManager.GetString("BubbleChartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bubble Chart.
        /// </summary>
        public static string BubbleChartTitle {
            get {
                return ResourceManager.GetString("BubbleChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Element.
        /// </summary>
        public static string ChartElement {
            get {
                return ResourceManager.GetString("ChartElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Type.
        /// </summary>
        public static string ChartType {
            get {
                return ResourceManager.GetString("ChartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows conditional formatting by customizing plot elements..
        /// </summary>
        public static string ConditionalFormattingDescription {
            get {
                return ResourceManager.GetString("ConditionalFormattingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional Formatting.
        /// </summary>
        public static string ConditionalFormattingTitle {
            get {
                return ResourceManager.GetString("ConditionalFormattingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows customized axis style and label format..
        /// </summary>
        public static string CustomizingAxesDescription {
            get {
                return ResourceManager.GetString("CustomizingAxesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customizing Axes.
        /// </summary>
        public static string CustomizingAxesTitle {
            get {
                return ResourceManager.GetString("CustomizingAxesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to fully customize plot elements..
        /// </summary>
        public static string CustomPlotElementsDescription {
            get {
                return ResourceManager.GetString("CustomPlotElementsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Plot Elements.
        /// </summary>
        public static string CustomPlotElementsTitle {
            get {
                return ResourceManager.GetString("CustomPlotElementsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a customized tooltip..
        /// </summary>
        public static string CustomTooltipsDescription {
            get {
                return ResourceManager.GetString("CustomTooltipsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Tooltips.
        /// </summary>
        public static string CustomTooltipsTitle {
            get {
                return ResourceManager.GetString("CustomTooltipsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a simple chart with static data labels..
        /// </summary>
        public static string DataLabelsDescription {
            get {
                return ResourceManager.GetString("DataLabelsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Labels.
        /// </summary>
        public static string DataLabelsTitle {
            get {
                return ResourceManager.GetString("DataLabelsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a dynamic, “live” chart..
        /// </summary>
        public static string DynamicChartDescription {
            get {
                return ResourceManager.GetString("DynamicChartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic Charts.
        /// </summary>
        public static string DynamicChartTitle {
            get {
                return ResourceManager.GetString("DynamicChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to export an image of FlexChart..
        /// </summary>
        public static string ExportImageDescription {
            get {
                return ResourceManager.GetString("ExportImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Image.
        /// </summary>
        public static string ExportImageTitle {
            get {
                return ResourceManager.GetString("ExportImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows stock data in a candle chart..
        /// </summary>
        public static string FinancialChartDescription {
            get {
                return ResourceManager.GetString("FinancialChartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Chart.
        /// </summary>
        public static string FinancialChartTitle {
            get {
                return ResourceManager.GetString("FinancialChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer.
        /// </summary>
        public static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a simple chart with tooltips..
        /// </summary>
        public static string GettingStartedDescription {
            get {
                return ResourceManager.GetString("GettingStartedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started.
        /// </summary>
        public static string GettingStartedTitle {
            get {
                return ResourceManager.GetString("GettingStartedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows Histogram Chart..
        /// </summary>
        public static string HistogramDescription {
            get {
                return ResourceManager.GetString("HistogramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histogram Chart.
        /// </summary>
        public static string HistogramTitle {
            get {
                return ResourceManager.GetString("HistogramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrates use of the FlexChart&apos;s hitTest method..
        /// </summary>
        public static string HitTestDescription {
            get {
                return ResourceManager.GetString("HitTestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit Test.
        /// </summary>
        public static string HitTestTitle {
            get {
                return ResourceManager.GetString("HitTestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image has been saved to your device&apos;s picture album..
        /// </summary>
        public static string ImageSavedDescription {
            get {
                return ResourceManager.GetString("ImageSavedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Saved.
        /// </summary>
        public static string ImageSavedTitle {
            get {
                return ResourceManager.GetString("ImageSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner Radius.
        /// </summary>
        public static string InnerRadius {
            get {
                return ResourceManager.GetString("InnerRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction.
        /// </summary>
        public static string Interaction {
            get {
                return ResourceManager.GetString("Interaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAnimated.
        /// </summary>
        public static string IsAnimated {
            get {
                return ResourceManager.GetString("IsAnimated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Position.
        /// </summary>
        public static string LabelPosition {
            get {
                return ResourceManager.GetString("LabelPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend Position.
        /// </summary>
        public static string LegendPosition {
            get {
                return ResourceManager.GetString("LegendPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows basic chart headers and axis titles..
        /// </summary>
        public static string LegendSampleDescription {
            get {
                return ResourceManager.GetString("LegendSampleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend and Titles.
        /// </summary>
        public static string LegendSampleTitle {
            get {
                return ResourceManager.GetString("LegendSampleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Marker Alignment.
        /// </summary>
        public static string LineMarkerAlignment {
            get {
                return ResourceManager.GetString("LineMarkerAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a moveable marker on top of the chart..
        /// </summary>
        public static string LineMarkerDescription {
            get {
                return ResourceManager.GetString("LineMarkerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Marker.
        /// </summary>
        public static string LineMarkerTitle {
            get {
                return ResourceManager.GetString("LineMarkerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Type.
        /// </summary>
        public static string LineType {
            get {
                return ResourceManager.GetString("LineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows animation modes when data is loaded..
        /// </summary>
        public static string LoadAnimationDescription {
            get {
                return ResourceManager.GetString("LoadAnimationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Animation Mode.
        /// </summary>
        public static string LoadAnimationTitle {
            get {
                return ResourceManager.GetString("LoadAnimationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a composite chart..
        /// </summary>
        public static string MixedChartTypesDescription {
            get {
                return ResourceManager.GetString("MixedChartTypesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed Chart Types.
        /// </summary>
        public static string MixedChartTypesTitle {
            get {
                return ResourceManager.GetString("MixedChartTypesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a chart with mutiple Y axes..
        /// </summary>
        public static string MultipleAxesDescription {
            get {
                return ResourceManager.GetString("MultipleAxesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Axes.
        /// </summary>
        public static string MultipleAxesTitle {
            get {
                return ResourceManager.GetString("MultipleAxesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        public static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKTitle {
            get {
                return ResourceManager.GetString("OKTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The permission is denied by user..
        /// </summary>
        public static string PermissionDenied {
            get {
                return ResourceManager.GetString("PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows inner radius, offset, and start angle..
        /// </summary>
        public static string PieBasicFeaturesDescription {
            get {
                return ResourceManager.GetString("PieBasicFeaturesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Features.
        /// </summary>
        public static string PieBasicFeaturesTitle {
            get {
                return ResourceManager.GetString("PieBasicFeaturesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows static data labels..
        /// </summary>
        public static string PieDataLabelsDescription {
            get {
                return ResourceManager.GetString("PieDataLabelsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Labels.
        /// </summary>
        public static string PieDataLabelsTitle {
            get {
                return ResourceManager.GetString("PieDataLabelsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a simple pie chart with tooltips..
        /// </summary>
        public static string PieGettingStartedDescription {
            get {
                return ResourceManager.GetString("PieGettingStartedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started.
        /// </summary>
        public static string PieGettingStartedTitle {
            get {
                return ResourceManager.GetString("PieGettingStartedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows basic header, footer, and legend positioning..
        /// </summary>
        public static string PieLegendSampleDescription {
            get {
                return ResourceManager.GetString("PieLegendSampleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend and Titles.
        /// </summary>
        public static string PieLegendSampleTitle {
            get {
                return ResourceManager.GetString("PieLegendSampleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows selection animation, offset, and position..
        /// </summary>
        public static string PieSelectionDescription {
            get {
                return ResourceManager.GetString("PieSelectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        public static string PieSelectionTitle {
            get {
                return ResourceManager.GetString("PieSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows available palettes..
        /// </summary>
        public static string PieThemingDescription {
            get {
                return ResourceManager.GetString("PieThemingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theming.
        /// </summary>
        public static string PieThemingTitle {
            get {
                return ResourceManager.GetString("PieThemingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Index.
        /// </summary>
        public static string PointIndex {
            get {
                return ResourceManager.GetString("PointIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemovePoint {
            get {
                return ResourceManager.GetString("RemovePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reversed.
        /// </summary>
        public static string Reversed {
            get {
                return ResourceManager.GetString("Reversed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotated.
        /// </summary>
        public static string Rotated {
            get {
                return ResourceManager.GetString("Rotated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a chart with panning (or scrolling) along the axes..
        /// </summary>
        public static string ScrollingDescription {
            get {
                return ResourceManager.GetString("ScrollingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrolling.
        /// </summary>
        public static string ScrollingTitle {
            get {
                return ResourceManager.GetString("ScrollingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag to scroll/Pinch to zoom.
        /// </summary>
        public static string ScrollZoomInstructions {
            get {
                return ResourceManager.GetString("ScrollZoomInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Item Offset.
        /// </summary>
        public static string SelectedItemOffset {
            get {
                return ResourceManager.GetString("SelectedItemOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Item Position.
        /// </summary>
        public static string SelectedItemPosition {
            get {
                return ResourceManager.GetString("SelectedItemPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Mode.
        /// </summary>
        public static string SelectionMode {
            get {
                return ResourceManager.GetString("SelectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the different selection modes..
        /// </summary>
        public static string SelectionModesDescription {
            get {
                return ResourceManager.GetString("SelectionModesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Modes.
        /// </summary>
        public static string SelectionModesTitle {
            get {
                return ResourceManager.GetString("SelectionModesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        public static string Series {
            get {
                return ResourceManager.GetString("Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacking.
        /// </summary>
        public static string Stacking {
            get {
                return ResourceManager.GetString("Stacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Angle.
        /// </summary>
        public static string StartAngle {
            get {
                return ResourceManager.GetString("StartAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows custom series styling..
        /// </summary>
        public static string StylingSeriesDescription {
            get {
                return ResourceManager.GetString("StylingSeriesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styling Series.
        /// </summary>
        public static string StylingSeriesTitle {
            get {
                return ResourceManager.GetString("StylingSeriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a simple sunburst chart.
        /// </summary>
        public static string SunburstGettingStartDescription {
            get {
                return ResourceManager.GetString("SunburstGettingStartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunburst Getting Started.
        /// </summary>
        public static string SunburstGettingStartTitle {
            get {
                return ResourceManager.GetString("SunburstGettingStartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take snapshot.
        /// </summary>
        public static string TakeSnapshot {
            get {
                return ResourceManager.GetString("TakeSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the built-in palettes..
        /// </summary>
        public static string ThemingDescription {
            get {
                return ResourceManager.GetString("ThemingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theming.
        /// </summary>
        public static string ThemingTitle {
            get {
                return ResourceManager.GetString("ThemingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theming.
        /// </summary>
        public static string Therming {
            get {
                return ResourceManager.GetString("Therming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the ability to toggle a series visibility..
        /// </summary>
        public static string ToggleSeriesDescription {
            get {
                return ResourceManager.GetString("ToggleSeriesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Series.
        /// </summary>
        public static string ToggleSeriesTitle {
            get {
                return ResourceManager.GetString("ToggleSeriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows animation when data is updated..
        /// </summary>
        public static string UpdateAnimationDescription {
            get {
                return ResourceManager.GetString("UpdateAnimationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Animation.
        /// </summary>
        public static string UpdateAnimationTitle {
            get {
                return ResourceManager.GetString("UpdateAnimationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Position.
        /// </summary>
        public static string UpdatePosition {
            get {
                return ResourceManager.GetString("UpdatePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Postion.
        /// </summary>
        public static string VerticalPostion {
            get {
                return ResourceManager.GetString("VerticalPostion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Y Values.
        /// </summary>
        public static string XYValues {
            get {
                return ResourceManager.GetString("XYValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a zones sample.
        /// </summary>
        public static string ZonesDescription {
            get {
                return ResourceManager.GetString("ZonesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zones.
        /// </summary>
        public static string ZonesTitle {
            get {
                return ResourceManager.GetString("ZonesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows stretch zoom-out and pinch zoom-in gestures..
        /// </summary>
        public static string ZoomingScrollingDescription {
            get {
                return ResourceManager.GetString("ZoomingScrollingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zooming and Scrolling.
        /// </summary>
        public static string ZoomingScrollingTitle {
            get {
                return ResourceManager.GetString("ZoomingScrollingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Mode.
        /// </summary>
        public static string ZoomMode {
            get {
                return ResourceManager.GetString("ZoomMode", resourceCulture);
            }
        }
    }
}
