// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Sunburst101
{
	public partial class FlexPieSelectionSampleController : UIViewController
	{
		public FlexPieSelectionSampleController (IntPtr handle) : base (handle)
		{
		}
	}
}
